'use client';
import {WebsiteText,WebsiteElement} from '@/app/WebsiteLanguage';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {CompletedScoreOffer} from '@/lib/game/completed-score-offer';
export default function GlobalScoreStatus(){
 const [message,setMessage]=useState('');
 const [offer,setOffer]=useState<CompletedScoreOffer|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[target,setTarget]=useState<Element|null>(null);
 const dialog=useRef<HTMLElement>(null),nameInput=useRef<HTMLInputElement>(null);
 const dismiss=()=>{if(busy)return;setOffer(null);requestAnimationFrame(()=>document.querySelector<HTMLCanvasElement>('.launcher-game-session .launcher-screen canvas')?.focus({preventScroll:true}));};
 useEffect(()=>{setTarget(document.querySelector('.launcher-game-session .launcher-screen'));setConsent(false);},[offer]);
 useEffect(()=>{if(!offer||!target)return;const game=target.querySelector<HTMLCanvasElement>('canvas');if(game)game.inert=true;nameInput.current?.focus({preventScroll:true});return()=>{if(game)game.inert=false;};},[offer,target]);
 useEffect(()=>{const update=(event:Event)=>{setOffer((event as CustomEvent<CompletedScoreOffer|null>).detail);setMessage('');};window.addEventListener('stunts-completed-score',update);return()=>window.removeEventListener('stunts-completed-score',update);},[]);
 async function submit(){if(!offer||busy||!consent)return;setBusy(true);try{const result=await offer.submit(name);if(result!=='rejected'){setOffer(null);requestAnimationFrame(()=>document.querySelector<HTMLCanvasElement>('.launcher-game-session .launcher-screen canvas')?.focus({preventScroll:true}));}}catch(error){setMessage(error instanceof Error?error.message:'Could not submit this run.');}finally{setBusy(false);}}
 useEffect(()=>{const update=(event:Event)=>{const detail=(event as CustomEvent<unknown>).detail;if(typeof detail==='string')setMessage(detail);};window.addEventListener('stunts-global-score-status',update);return()=>window.removeEventListener('stunts-global-score-status',update);},[]);
 const panel=offer&&<div className="completed-score-backdrop" onKeyDown={event=>{event.stopPropagation();if(event.key==='Escape'){event.preventDefault();dismiss();}if(event.key==='Tab'){const items=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled)');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}}><section ref={dialog} className="completed-score-offer" role="dialog" aria-modal="true" aria-labelledby="completed-score-heading"><WebsiteElement as="button" className="completed-score-close" type="button" disabled={busy} onClick={dismiss} aria-label="Close">×</WebsiteElement><h3 id="completed-score-heading"><WebsiteText text="Submit your completed run"/></h3><p><WebsiteText text="Outside the in-game top seven? You can still submit this run."/></p><p className="completed-score-summary"><span><strong>{offer.track}</strong>{offer.car&&<small className="completed-score-car">{offer.car}</small>}</span><strong>{Math.floor(offer.ticks/1200)}:{String(Math.floor(offer.ticks/20)%60).padStart(2,'0')}.{String((offer.ticks%20)*5).padStart(2,'0')}</strong></p><form onSubmit={event=>{event.preventDefault();if(consent)void submit();}}><label><WebsiteText text="Driver name"/><input ref={nameInput} value={name} disabled={busy} maxLength={16} required onChange={event=>setName(event.target.value)} autoComplete="nickname"/></label><label className="completed-score-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={event=>setConsent(event.target.checked)}/><WebsiteText text="Publish my score and replay"/></label><p><WebsiteText text="Your replay will be checked automatically."/></p><div className="completed-score-actions"><button type="button" disabled={busy} onClick={dismiss}><WebsiteText text="Not now"/></button><button type="submit" disabled={busy||!name.trim()||!consent}><WebsiteText text="Submit score and replay"/></button></div></form><p><WebsiteText text="This does not change your in-game high scores."/></p><p role="status" aria-live="polite"><WebsiteText text={message}/></p></section></div>;
 return <>{panel&&(target?createPortal(panel,target):panel)}<p className="global-score-status" role="status" aria-live="polite"><WebsiteText text={offer?'':message}/></p></>;
}
