'use client';
import {useEffect,useState} from 'react';
import {Trophy,TrendingUp,Check,Flag} from 'lucide-react';
import {WebsiteText,useWebsiteLocale} from './WebsiteLanguage';
type Race={id:string;driver:string;track:string;car:string;ticks:number;postedAt:number;event:string;improvement:number|null};
const time=(ticks:number)=>`${Math.floor(ticks/1200)}:${String(Math.floor(ticks/20)%60).padStart(2,'0')}.${String((ticks%20)*5).padStart(2,'0')}`;
const labels:Record<string,string>={record:'set a new valid track record',improved:'improved their time',valid:'completed a valid run',submitted:'submitted a run'};
export default function RecentRacesPanel(){
 const locale=useWebsiteLocale(),[races,setRaces]=useState<Race[]>([]),[state,setState]=useState('loading'),[now,setNow]=useState(Date.now());
 useEffect(()=>{const controller=new AbortController();let pending=false;const refresh=async()=>{if(pending||document.hidden)return;pending=true;try{const response=await fetch('/api/recent-races',{signal:controller.signal});if(!response.ok)throw Error('Unavailable');const body=await response.json() as {races:Race[]};if(!controller.signal.aborted){setRaces(body.races.slice(0,5));setState('ready');setNow(Date.now());}}catch{if(!controller.signal.aborted)setState('error');}finally{pending=false;}};void refresh();const timer=setInterval(()=>void refresh(),60000);const visible=()=>{if(!document.hidden)void refresh();};document.addEventListener('visibilitychange',visible);return()=>{controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[]);
 const relative=(stamp:number)=>{const seconds=Math.max(0,Math.floor(now/1000)-stamp);const unit=seconds<3600?'minute':seconds<86400?'hour':'day';const value=Math.floor(seconds/(unit==='minute'?60:unit==='hour'?3600:86400));return new Intl.RelativeTimeFormat(locale,{numeric:'auto'}).format(-value,unit);};
 return <section className="recent-races-panel" aria-labelledby="recent-races-heading"><h3 id="recent-races-heading"><WebsiteText text="RECENT RACES"/><span aria-hidden="true"/></h3>{state==='loading'?<p><WebsiteText text="Loading recent races…"/></p>:state==='error'&&!races.length?<p><WebsiteText text="Recent races are temporarily unavailable."/></p>:!races.length?<p><WebsiteText text="No public races yet."/></p>:<ol>{races.map(race=>{const Icon=race.event==='record'?Trophy:race.event==='improved'?TrendingUp:race.event==='valid'?Check:Flag;return <li key={race.id}><Icon size={18} aria-hidden="true"/><div><p><strong>{race.driver}</strong> <WebsiteText text={labels[race.event]??labels.submitted}/></p><small>{race.track} · {race.car}</small><div className="recent-race-result"><strong>{time(race.ticks)}{race.improvement!==null&&<span> · −{(race.improvement/20).toFixed(2)}s</span>}</strong><time dateTime={new Date(race.postedAt*1000).toISOString()}>{relative(race.postedAt)}</time></div></div></li>;})}</ol>}<footer><small><WebsiteText text="Latest five public submissions"/></small><a href="/high-scores"><WebsiteText text="View leaderboards"/></a></footer></section>;
}
