'use client';
import { useEffect,useRef,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Maximize,Pause,Play,RotateCcw,Save,Settings2,Volume2 } from 'lucide-react';
import Garage from './Garage';
import NativeDrive from './NativeDrive';
import OpeningSequence from './OpeningSequence';
import { startReference,type Reference } from '@/lib/game/reference';
import type { Assets } from '@/lib/game/types';
export default function ReferenceHome(){
 const [mode,setMode]=useState<'home'|'game'|'garage'|'native'|'opening'>('home');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [paused,setPaused]=useState(false);const [volume,setVolume]=useState(80);const [smooth,setSmooth]=useState(false);const [assets,setAssets]=useState<Assets|null>(null);const [error,setError]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null);const screen=useRef<HTMLDivElement>(null);const runtime=useRef<Reference|null>(null);const alive=useRef(true);
 useEffect(()=>{alive.current=true;if(new URLSearchParams(window.location.search).has('opening-check'))setMode('opening');fetch('/game/assets.json').then(r=>{if(!r.ok)throw Error('Asset loading failed');return r.json()}).then(d=>{if(alive.current)setAssets(d as Assets)}).catch(()=>{if(alive.current)setError('The 3D car files could not load. You can still start the original game.')});return()=>{alive.current=false;void runtime.current?.stop()}},[]);
 async function start(setup=false){if(busy)return;setBusy(true);setError('');setNotice('Starting…');setMode('game');setPaused(false);const audio=new AudioContext({latencyHint:'interactive'});void audio.resume();try{if(runtime.current){await runtime.current.stop();runtime.current=null}const game=await startReference(canvas.current!,audio,setup,s=>{if(alive.current)setNotice(s)});if(!alive.current){await game.stop();return}runtime.current=game;game.volume(volume/100)}catch(e){await audio.close().catch(()=>{});setError(e instanceof Error?e.message:'Could not start the game.')}finally{if(alive.current)setBusy(false)}}
 async function back(){setBusy(true);try{await runtime.current?.stop();runtime.current=null;setMode('home');setPaused(false)}catch{setError('Could not save this session. Please keep the game open.')}finally{setBusy(false)}}
 function pause(){if(!runtime.current)return;runtime.current.release();if(paused){runtime.current.ci.resume();canvas.current?.focus()}else runtime.current.ci.pause();setPaused(!paused)}
 async function save(){if(!runtime.current)return;try{await runtime.current.save();setNotice('Game files saved in this browser.')}catch{setError('Saving failed. Keep this tab open so your current files remain available.')}}
 return <main className="game-shell"><header><button className="wordmark" onClick={()=>{if(mode==='garage'||mode==='native'||mode==='opening')setMode('home')}} aria-label="Stunts home">STUNTS</button><div className="version-links"><span>Original reference</span><a href="/">← Native reconstruction</a></div></header>
 {mode==='home'&&<section className="start-grid"><div className="start-copy"><p className="eyebrow">4D SPORTS DRIVING</p><h1>Stunts</h1><p className="intro">Your original cars, tracks, menus and sound.</p><Button className="drive-button" onClick={()=>void start()}>Play original reference <Play size={18}/></Button><div className="start-actions"><Button variant="outline" onClick={()=>void start(true)}><Settings2 size={16}/> Game setup</Button><Button variant="outline" disabled={!assets} onClick={()=>setMode('garage')}>Explore 3D cars →</Button><Button variant="outline" disabled={!assets} onClick={()=>setMode('opening')}>Watch rebuilt opening →</Button></div><p className="fine">Play the original as a reference, or return to the native reconstruction using the link above.</p></div><div className="track-board"><img src="/game/menu.png" alt="The original Stunts main menu" className="menu-preview"/><div className="edition-tag">1.1 / DEC 13 1990</div></div></section>}
 <section className="play-area" style={{display:mode==='game'?'block':'none'}}><div className="game-toolbar"><Button variant="outline" disabled={busy} onClick={()=>void back()}>← Back</Button><div className="toolbar-group"><Button variant="ghost" disabled={busy||!runtime.current} onClick={pause}>{paused?<Play/>:<Pause/>}{paused?'Resume':'Pause'}</Button><Button variant="ghost" disabled={busy} onClick={()=>void start()}><RotateCcw/>Restart</Button><Button variant="ghost" disabled={busy||!runtime.current} onClick={()=>void save()}><Save/>Save files</Button><Button variant="ghost" onClick={()=>void screen.current?.requestFullscreen().catch(()=>setError('Fullscreen is unavailable. You can enlarge the browser window instead.'))}><Maximize/>Fullscreen</Button></div></div><div className="game-screen" ref={screen}><canvas ref={canvas} width={320} height={200} tabIndex={0} aria-label="Original Stunts game. Click here to use the keyboard." style={{imageRendering:smooth?'auto':'pixelated'}}/>{busy&&<div className="screen-message" role="status">{notice}</div>}{paused&&<button className="screen-message" onClick={pause}>Paused · click to resume</button>}</div><div className="game-settings"><div className="volume"><Volume2 size={18}/><span id="volume-label">Volume</span><Slider aria-labelledby="volume-label" value={[volume]} min={0} max={100} step={1} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;setVolume(n);runtime.current?.volume(n/100)}}/><span>{volume}%</span></div><Select value={smooth?'smooth':'sharp'} onValueChange={v=>setSmooth(v==='smooth')}><SelectTrigger aria-label="Display scaling"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sharp">Sharp pixels</SelectItem><SelectItem value="smooth">Smooth scaling</SelectItem></SelectContent></Select><span className="fine">Original 4:3 display · click the game for keyboard control</span></div><p className="status" role="status">{notice}</p><div className="control-strip"><span><kbd>↑</kbd><kbd>↓</kbd> Accelerate / brake</span><span><kbd>←</kbd><kbd>→</kbd> Steer</span><span><kbd>Enter</kbd> Continue</span><span><kbd>Esc</kbd> Game menu</span></div><p className="fine">Save a track or replay inside the original game, then use Save files to keep it in this browser. Game setup is available from the start screen.</p></section>
 {mode==='opening'&&assets&&<OpeningSequence assets={assets} onBack={()=>setMode('home')}/>}
 {mode==='native'&&assets&&<NativeDrive assets={assets} onBack={()=>setMode('home')}/>}
 {mode==='garage'&&assets&&<Garage assets={assets}/>}
 {error&&<p role="alert" className="error">{error}</p>}
 <footer><span>Original game by Distinctive Software · browser reconstruction in progress</span><span>Keyboard recommended · saves stay in this browser</span></footer></main>
}
