'use client';
import {useRef,useState} from 'react';
import {prepareReplayUpload} from '@/lib/game/replay-upload';
import {prepareTrackUpload} from '@/lib/game/track-upload';
import {type NativeStoredFile,openNativeFilePersistence} from '@/lib/game/native-file-store';
import {NATIVE_GAME_DIRECTORY_KEY} from '@/lib/game/browser-setup-selection';
import {encodeSaveBackup,decodeSaveBackup} from '@/lib/game/save-backup';
export default function SaveBackupPanel({running}:{running:boolean}){
 const dialog=useRef<HTMLDialogElement>(null),[downloads,setDownloads]=useState<NativeStoredFile[]>([]);
 async function showDownloads(){setBusy(true);try{const db=await openNativeFilePersistence();try{setDownloads((await db.all()).filter(f=>/\.(TRK|RPL)$/i.test(f.key)).sort((a,b)=>a.key.localeCompare(b.key)));}finally{db.close?.();}dialog.current?.showModal();}catch(e){setMessage(e instanceof Error?e.message:'Could not load saved files.');}finally{setBusy(false);}}
 function downloadFile(file:NativeStoredFile){const name=file.key.split(/[\\/]/).pop()!,url=URL.createObjectURL(new Blob([new Uint8Array(file.bytes)],{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`${name} downloaded.`);}
 const replayInput=useRef<HTMLInputElement>(null),trackInput=useRef<HTMLInputElement>(null),input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function backup(){setBusy(true);try{const db=await openNativeFilePersistence();let files;try{files=await db.all();}finally{db.close?.();}const text=encodeSaveBackup(files,localStorage.getItem(NATIVE_GAME_DIRECTORY_KEY)??'C:\\'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stunts-saves-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`Backup downloaded: ${files.length} saved files.`);}catch(e){setMessage(e instanceof Error?e.message:'Backup failed.');}finally{setBusy(false);}}
 async function restore(file:File){setBusy(true);try{if(file.size>32*1024*1024)throw Error('Backup is too large (maximum 32 MB).');const backup=decodeSaveBackup(await file.text()),db=await openNativeFilePersistence();let count;try{count=await db.merge(backup.files);}finally{db.close?.();}if(!localStorage.getItem(NATIVE_GAME_DIRECTORY_KEY))localStorage.setItem(NATIVE_GAME_DIRECTORY_KEY,backup.directory);setMessage(`Imported ${count} files. Existing files were kept. Reload the page before playing.`);}catch(e){setMessage(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function uploadTrack(file:File){setBusy(true);try{if(file.size!==1802)throw Error('Original Stunts .TRK files must be exactly 1,802 bytes.');const track=prepareTrackUpload(file.name,new Uint8Array(await file.arrayBuffer()),localStorage.getItem(NATIVE_GAME_DIRECTORY_KEY)??'C:\\'),db=await openNativeFilePersistence();let count;try{count=await db.merge([track]);}finally{db.close?.();}setMessage(count?`Track ${file.name.toUpperCase()} imported. Press Play, then open Track and load it from the game’s track menu.`:'A track with that name already exists. Rename your file to import another copy.');}catch(e){setMessage(e instanceof Error?e.message:'Track upload failed.');}finally{setBusy(false);if(trackInput.current)trackInput.current.value='';}}
 async function uploadReplay(file:File){setBusy(true);try{if(file.size>0x722+65535)throw Error('Replay file is too large.');const replay=prepareReplayUpload(file.name,new Uint8Array(await file.arrayBuffer()),localStorage.getItem(NATIVE_GAME_DIRECTORY_KEY)??'C:\\'),db=await openNativeFilePersistence();let count;try{count=await db.merge([replay]);}finally{db.close?.();}setMessage(count?`Replay ${file.name.toUpperCase()} imported. Press Play, then open the replay menu and load it.`:'A replay with that name already exists. Rename your file to import another copy.');}catch(e){setMessage(e instanceof Error?e.message:'Replay upload failed.');}finally{setBusy(false);if(replayInput.current)replayInput.current.value='';}}
 return <details id="saves"><summary>Tracks, replays and save backups</summary><p>Tracks, replays and settings stay in this browser, on this website address. Clearing browser data can erase them. Download a backup to keep a copy.</p><p>Upload an original <strong>.TRK</strong> track (1,802 bytes) or <strong>.RPL</strong> replay, then load it from the game’s track or replay menu. Files stay in this browser.</p><button onClick={()=>trackInput.current?.click()} disabled={busy||running}>Upload track (.TRK)</button><input ref={trackInput} type="file" accept=".trk" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void uploadTrack(f);}}/>{' '}<button onClick={()=>replayInput.current?.click()} disabled={busy||running}>Upload replay (.RPL)</button><input ref={replayInput} type="file" accept=".rpl" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void uploadReplay(f);}}/>{' '}<button onClick={()=>void showDownloads()} disabled={busy}>Download tracks &amp; replays</button>{' '}<button onClick={backup} disabled={busy}>Download backup</button>{' '}<button onClick={()=>input.current?.click()} disabled={busy||running}>Import backup</button><input ref={input} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f);}}/>{running&&<p>To import, reload this page and import before pressing Play. Save your current run first.</p>}<p role="status">{message}</p><dialog ref={dialog} className="saved-file-dialog" aria-labelledby="saved-file-title"><div className="saved-file-heading"><h2 id="saved-file-title">Download tracks &amp; replays</h2><button onClick={()=>dialog.current?.close()} aria-label="Close downloads">Close</button></div><p>Save your track or replay in the game first. These are the original .TRK and .RPL files, ready to copy into your DOS Stunts folder.</p>{downloads.length?<ul className="saved-file-list">{downloads.map(file=><li key={file.key}><span><strong>{file.key.split(/[\\/]/).pop()}</strong><small>{file.key} · {file.bytes.length.toLocaleString()} bytes</small></span><button onClick={()=>downloadFile(file)} aria-label={`Download ${file.key}`}>Download</button></li>)}</ul>:<p>No saved tracks or replays yet. Save one in the game, then reopen this window.</p>}<p role="status">{message}</p></dialog></details>;
}
