'use client';
import {WebsiteText,WebsiteElement} from '@/app/WebsiteLanguage';
import {useEffect,useState} from 'react';
import {openNativeFilePersistence,nativeFileKey} from '@/lib/game/native-file-store';
import {NATIVE_GAME_DIRECTORY_KEY} from '@/lib/game/browser-setup-selection';
import {scoreString,scoreTicks,MAX_RANKED_FRAMES,GLOBAL_SCORE_DATABASE,type GlobalScoreSubmission} from '@/lib/game/global-score-format';
import {validateReplayEncoding} from '@/lib/game/upload-validation';
import {routeDisplay} from '@/lib/server/route-display';
import type {RouteAssessment} from '@/lib/server/shortcut-assessment';
type Replay={id:string;track:string;car:string;ticks:number;driver:string;trackName:string};
const time=(ticks:number)=>`${Math.floor(ticks/1200)}:${(Math.floor(ticks/20)%60).toString().padStart(2,'0')}.${((ticks%20)*5).toString().padStart(2,'0')}`;
export default function SharedReplaysPanel({running}:{running:boolean}){
 const [mine,setMine]=useState<{id:string;proof:GlobalScoreSubmission}[]>([]),[replays,setReplays]=useState<Replay[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{const update=()=>{if(loaded)void load();};window.addEventListener('stunts-public-replay-shared',update);return()=>window.removeEventListener('stunts-public-replay-shared',update);},[loaded]);
useEffect(()=>{let closed=false;const refresh=async()=>{const db=await openNativeFilePersistence(GLOBAL_SCORE_DATABASE);try{const files=await db.all();if(!closed)setMine(files.filter(file=>file.key.startsWith('VERIFIED:')&&file.bytes.length).map(file=>({id:file.key.slice(9),proof:JSON.parse(new TextDecoder().decode(file.bytes)) as GlobalScoreSubmission})));}finally{db.close?.();}};void refresh();window.addEventListener('stunts-verified-replays',refresh);return()=>{closed=true;window.removeEventListener('stunts-verified-replays',refresh);};},[]);
 async function load(){setBusy(true);try{const response=await fetch('/api/replays',{cache:'no-store'}),body=await response.json() as {replays:Replay[];error?:string};if(!response.ok)throw Error(body.error);setReplays(body.replays);setLoaded(true);}catch(error){setMessage(error instanceof Error?error.message:'Could not load replays');}finally{setBusy(false);}}
 async function share(proof:GlobalScoreSubmission){setBusy(true);try{const response=await fetch('/api/replays',{method:'POST',headers:{'Content-Type':'application/json','X-Stunts-Replay':'share'},body:JSON.stringify(proof)}),body=await response.json() as {error?:string};if(!response.ok)throw Error(body.error);setMessage('Replay shared. Everyone can now watch the verified run.');await load();}catch(error){setMessage(error instanceof Error?error.message:'Could not share replay');}finally{setBusy(false);}}
 async function recheck(proof:GlobalScoreSubmission){setBusy(true);try{const response=await fetch('/api/replays',{method:'POST',headers:{'Content-Type':'application/json','X-Stunts-Replay':'recheck'},body:JSON.stringify(proof)}),body=await response.json() as {error?:string;routeAssessment?:RouteAssessment};if(!response.ok)throw Error(body.error);setMessage('Privately rechecked: '+routeDisplay(body.routeAssessment).label+'. Classification updated; this did not publish your replay. Refresh High Scores to see the result.');}catch(error){setMessage(error instanceof Error?error.message:'Could not privately recheck this run');}finally{setBusy(false);}}
 async function add(replay:Replay){setBusy(true);try{const response=await fetch('/api/replays?id='+replay.id);if(!response.ok)throw Error('Replay is no longer available');const bytes=new Uint8Array(await response.arrayBuffer());validateReplayEncoding(bytes,MAX_RANKED_FRAMES);const trackName=scoreString(bytes,13,22),replayName='R'+replay.id.slice(0,7).toUpperCase(),directory=localStorage.getItem(NATIVE_GAME_DIRECTORY_KEY)??'C:\\',db=await openNativeFilePersistence();try{const files=[{key:nativeFileKey(directory,trackName,'.trk'),bytes:bytes.slice(24,0x722)},{key:nativeFileKey(directory,replayName,'.rpl'),bytes}],existing=await db.all();for(const file of files){const other=existing.find(item=>item.key===file.key);if(other&&(other.bytes.length!==file.bytes.length||!other.bytes.every((n,i)=>n===file.bytes[i])))throw Error('A file with this name already exists. Download and rename the replay instead.');}await db.merge(files);}finally{db.close?.();}setMessage(`${replayName} added. Press Play, then Options → Load Replay and select ${replayName}.`);}catch(error){setMessage(error instanceof Error?error.message:'Could not add replay');}finally{setBusy(false);}}
 return <details className="shared-tracks" onToggle={event=>{if(event.currentTarget.open&&!loaded&&!busy)void load();}}><summary><WebsiteText text={"High-score replays"}/></summary><p><WebsiteText text={"Submitting a high score also publishes its verified replay. Skip submission to keep the run private. Older private recordings are not published automatically."}/></p><button disabled={busy} onClick={()=>void load()}><WebsiteText text={"Refresh replays"}/></button><output aria-live="polite">{<WebsiteText text={message}/>}</output><h3><WebsiteText text={"Your verified runs"}/></h3>{!mine.length&&<p><WebsiteText text={"Finish a fresh race and confirm public replay sharing when submitting your score. The verified recording appears here and is published automatically."}/></p>}<ul>{mine.map(({id,proof})=><li key={id}><strong>{scoreString(proof.record,0,17)} · {scoreString(proof.replay,13,22)||<WebsiteText text={'Track'}/>} · {scoreString(proof.replay,0,4)} · {time(scoreTicks(proof.record))}</strong><button disabled={busy} onClick={()=>void recheck(proof)}><WebsiteText text={"Recheck privately"}/></button><button disabled={busy||replays.some(replay=>replay.id===id)} onClick={()=>void share(proof)}>{replays.some(replay=>replay.id===id)?<WebsiteText text={'Replay shared'}/>:<WebsiteText text={'Share replay'}/>}</button></li>)}</ul><h3><WebsiteText text={"Shared runs"}/></h3>{loaded&&!replays.length&&<p><WebsiteText text={"No shared replays yet."}/></p>}<ul>{replays.map(replay=><li key={replay.id}><strong>{replay.driver} · {replay.trackName} · {replay.car} · {time(replay.ticks)}</strong><div><button disabled={busy||running} onClick={()=>void add(replay)}><WebsiteText text={"Add replay to my game"}/></button><a href={'/api/replays?id='+replay.id} download><WebsiteText text={"Download .RPL"}/></a></div></li>)}</ul>{running&&<p><WebsiteText text={"Save your current run and restart the webpage game before adding a shared replay. Playback uses the original replay viewer and its camera controls."}/></p>}<p><WebsiteText text={"Replays remain available while ranked or among the driver’s five most recent verified runs on that track. The latest 50 shared runs are shown."}/></p></details>;
}
