'use client';
import {createContext,createElement,useContext,useEffect,useRef,useState,type ReactNode,type JSX} from 'react';
import {translateWebsite,type WebsiteLocale} from '@/lib/website-languages';
import Image from 'next/image';
import type {ComponentProps} from 'react';
const LanguageContext=createContext<{locale:WebsiteLocale;change:(locale:WebsiteLocale)=>void}>({locale:'en',change:()=>{}});
export function WebsiteLanguageProvider({children}:{children:ReactNode}){
 const [locale,setLocale]=useState<WebsiteLocale>('en');
 useEffect(()=>{try{const saved=localStorage.getItem('playstunts-website-language');if(saved==='es'||saved==='it')setLocale(saved);}catch{}},[]);
 useEffect(()=>{document.documentElement.lang=locale;const path=location.pathname;const kind=path==='/faq'?'FAQ':path==='/high-scores'?'High Scores':path==='/setup'?'Setup':'Play Stunts';const titles={en:{FAQ:'FAQ — Play Stunts','High Scores':'High Scores — Play Stunts',Setup:'Setup — Play Stunts','Play Stunts':'Play Stunts — The classic racing game in your browser'},es:{FAQ:'Preguntas frecuentes — Play Stunts','High Scores':'Récords — Play Stunts',Setup:'Configuración — Play Stunts','Play Stunts':'Play Stunts — El juego clásico de carreras en tu navegador'},it:{FAQ:'Domande frequenti — Play Stunts','High Scores':'Record — Play Stunts',Setup:'Configurazione — Play Stunts','Play Stunts':'Play Stunts — Il gioco di corse classico nel browser'}};document.title=titles[locale][kind];},[locale]);
 const change=(value:WebsiteLocale)=>{setLocale(value);try{localStorage.setItem('playstunts-website-language',value);}catch{}};
 return <LanguageContext.Provider value={{locale,change}}>{children}</LanguageContext.Provider>;
}
export function WebsiteText({text}:{text:string|undefined}){const {locale}=useContext(LanguageContext);return translateWebsite(text??'',locale);}
export function useWebsiteLocale(){return useContext(LanguageContext).locale;}
export function WebsiteImage(props:ComponentProps<typeof Image>){const {locale}=useContext(LanguageContext);return <Image {...props} alt={translateWebsite(props.alt,locale)}/>;}
// Translate presentation attributes only. Values, filenames, driver names,
// native keyboard inputs, canvas contents and score data are never rewritten.
export function WebsiteElement<T extends keyof JSX.IntrinsicElements>({as,...props}:{as:T}&JSX.IntrinsicElements[T]){const {locale}=useContext(LanguageContext);const translated:Record<string,unknown>={...props};for(const key of ['aria-label','title','placeholder','alt'])if(typeof translated[key]==='string')translated[key]=translateWebsite(translated[key] as string,locale);return createElement(as,translated);}
function LanguageFlag({locale}:{locale:WebsiteLocale}){return <svg className="website-language-flag" width="22" height="14" viewBox="0 0 30 20" aria-hidden="true">{locale==='it'?<><path fill="#009246" d="M0 0h10v20H0z"/><path fill="#fff" d="M10 0h10v20H10z"/><path fill="#ce2b37" d="M20 0h10v20H20z"/></>:locale==='es'?<><path fill="#aa151b" d="M0 0h30v20H0z"/><path fill="#f1bf00" d="M0 5h30v10H0z"/></>:<><path fill="#012169" d="M0 0h30v20H0z"/><path d="m0 0 30 20M30 0 0 20" stroke="#fff" strokeWidth="4"/><path d="m0 0 30 20M30 0 0 20" stroke="#c8102e" strokeWidth="1.5"/><path d="M15 0v20M0 10h30" stroke="#fff" strokeWidth="7"/><path d="M15 0v20M0 10h30" stroke="#c8102e" strokeWidth="4"/></>}</svg>;}
export function WebsiteLanguageSelector(){
 const {locale,change}=useContext(LanguageContext),menu=useRef<HTMLDetailsElement>(null);
 const choices=[['en','English'],['es','Español'],['it','Italiano']] as const;
 useEffect(()=>{const outside=(event:PointerEvent)=>{if(!menu.current?.contains(event.target as Node))menu.current?.removeAttribute('open');};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 return <div className="website-language"><svg className="website-language-globe" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></svg><details ref={menu} className="website-language-dropdown" onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))event.currentTarget.removeAttribute('open');}} onKeyDown={event=>{const element=menu.current;if(!element)return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();element.removeAttribute('open');element.querySelector('summary')?.focus();}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();element.open=true;const buttons=Array.from(element.querySelectorAll<HTMLButtonElement>('[role=menuitemradio]')),index=buttons.indexOf(document.activeElement as HTMLButtonElement);const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:event.key==='ArrowDown'?(index+1)%buttons.length:(index<0?buttons.length-1:(index-1+buttons.length)%buttons.length);buttons[next]?.focus();}}}>
 <summary aria-label={translateWebsite('Website language',locale)} aria-haspopup="menu"><span>{choices.find(([value])=>value===locale)![1]}</span><LanguageFlag locale={locale}/><svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 9 6 6 6-6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg></summary>
 <div className="website-language-options" role="menu" aria-label={translateWebsite('Website language',locale)}>{choices.map(([value,label])=><button key={value} type="button" role="menuitemradio" aria-checked={value===locale} lang={value} onClick={()=>{change(value);menu.current?.removeAttribute('open');menu.current?.querySelector('summary')?.focus();}}><span>{label}</span><LanguageFlag locale={value}/><span aria-hidden="true">{value===locale?'✓':''}</span></button>)}</div>
 </details></div>;
}
