import {faqTranslations} from './website-faq-translations.ts';
import {statusTranslations} from './website-status-translations.ts';
export type WebsiteLocale='en'|'es'|'it';
// Each entry must include both translations. Keep keys identical to the
// English website copy; game/driver/track names are not translation keys.
export const websiteTranslations:Record<string,readonly [string,string]>={
 ...faqTranslations,
 ...statusTranslations,
 'Private — only in this browser':['Privado — solo en este navegador','Privato — solo in questo browser'],
 'Files imported here are for your own game. They are not shared with other players or synced between devices. Clearing browser data can erase them; download a backup to keep a copy.':['Los archivos importados aquí son para tu propio juego. No se comparten con otros jugadores ni se sincronizan entre dispositivos. Borrar los datos del navegador puede eliminarlos; descarga una copia de seguridad para conservarlos.','I file importati qui sono per il tuo gioco personale. Non vengono condivisi con altri giocatori né sincronizzati tra dispositivi. Cancellare i dati del browser può eliminarli; scarica una copia di sicurezza per conservarli.'],
 'Want everyone to play your track? Open':['¿Quieres que todos jueguen en tu pista? Abre','Vuoi che tutti possano giocare sulla tua pista? Apri'],
 'and choose Share track (.TRK).':['y elige Compartir circuito (.TRK).','e scegli Condividi pista (.TRK).'],
 'Why does my run say Possibly exploited?':['¿Por qué mi carrera dice Posible exploit?','Perché la mia gara indica Possibile exploit?'],
 'Hover, focus or tap the badge for a short assessment reason. Replay checks can identify grass transfers that skip sections, branch switching or a grass-speed exploit. Full route not confirmed means the evidence was inconclusive, not proof of cheating. The score remains eligible. Older runs without a retained public replay may only have a general explanation.':['Pasa el cursor, enfoca o toca la etiqueta para ver una breve razón de la evaluación. Los controles de la repetición pueden detectar cruces de hierba que saltan tramos, cambios entre ramales o un exploit de velocidad sobre hierba. Recorrido completo no confirmado significa que las pruebas fueron inconcluyentes, no que se haya demostrado una trampa. El tiempo sigue siendo válido para la clasificación. Las carreras antiguas sin una repetición pública conservada pueden tener solo una explicación general.','Passa il puntatore, seleziona con la tastiera o tocca l’etichetta per una breve motivazione. I controlli del replay possono rilevare attraversamenti dell’erba che saltano tratti, cambi tra rami o un exploit di velocità sull’erba. Percorso completo non confermato significa che le prove sono inconcludenti, non che sia stato dimostrato un imbroglio. Il tempo rimane idoneo alla classifica. Le vecchie gare senza un replay pubblico conservato possono avere solo una spiegazione generale.'],
 'Full route confirmed':['Recorrido completo confirmado','Percorso completo confermato'],
 'Grass-speed exploit':['Exploit de velocidad sobre hierba','Exploit di velocità sull’erba'],
 'Switched route branches':['Cambio entre ramales del recorrido','Cambio tra rami del percorso'],
 'Crossed grass to skip sections':['Cruzó hierba para saltar tramos','Attraversamento dell’erba per saltare tratti'],
 'Shortcut or exploit detected':['Atajo o exploit detectado','Scorciatoia o exploit rilevato'],
 'Grass-speed evidence inconclusive':['Pruebas de velocidad sobre hierba inconcluyentes','Prove di velocità sull’erba inconcludenti'],
 'Full route not confirmed':['Recorrido completo no confirmado','Percorso completo non confermato'],
 'Submission saved in this browser. Verification continues in the background.':['Envío guardado en este navegador. La verificación continúa en segundo plano.','Invio salvato in questo browser. La verifica continua in background.'],
 'The leaderboard keeps your best qualifying time. Your five most recent verified submissions can appear in recent runs with their public replays, including slower attempts. Full run is an assessed category, not a selectable racing mode.':['La clasificación conserva tu mejor tiempo válido. Tus cinco envíos verificados más recientes pueden aparecer con sus repeticiones públicas, incluidos los intentos más lentos. Carrera completa es una categoría evaluada, no un modo seleccionable.','La classifica conserva il tuo miglior tempo valido. I tuoi cinque invii verificati più recenti possono apparire con i replay pubblici, inclusi i tentativi più lenti. Gara completa è una categoria valutata, non una modalità selezionabile.'],
 'Submitting your high score also publishes your replay. Continue?':['Enviar tu récord también publica tu repetición. ¿Continuar?','Inviare il tuo record pubblica anche il replay. Continuare?'],
 'Run verified. Its replay is public while ranked or among your five most recent verified runs.':['Carrera verificada. Su repetición es pública mientras esté clasificada o entre tus cinco carreras verificadas más recientes.','Gara verificata. Il replay è pubblico finché è in classifica o tra le tue cinque gare verificate più recenti.'],
 'High-score submission cancelled. Nothing was uploaded.':['Envío del récord cancelado. No se ha subido nada.','Invio del record annullato. Non è stato caricato nulla.'],
 'Submitting a high score also publishes its verified replay. Skip submission to keep the run private. Older private recordings are not published automatically.':['Enviar un récord también publica su repetición verificada. Omite el envío para mantener la carrera privada. Las grabaciones privadas anteriores no se publican automáticamente.','Inviare un record pubblica anche il replay verificato. Salta l’invio per mantenere privata la gara. Le vecchie registrazioni private non vengono pubblicate automaticamente.'],
 'Finish a fresh race and confirm public replay sharing when submitting your score. The verified recording appears here and is published automatically.':['Completa una nueva carrera y confirma la publicación de la repetición al enviar tu tiempo. La grabación verificada aparece aquí y se publica automáticamente.','Completa una nuova gara e conferma la condivisione pubblica del replay quando invii il tempo. La registrazione verificata appare qui e viene pubblicata automaticamente.'],
 'Are replays required for high scores?':['¿Se requieren repeticiones para los récords?','I replay sono obbligatori per i record?'],
 'Yes. Submitting a high score requires confirmation that its replay will be public. The server verifies and stores the recording with the score. Skipping submission uploads nothing. Ordinary in-game replay saving stays private.':['Sí. Enviar un récord requiere confirmar que su repetición será pública. El servidor verifica y guarda la grabación junto con el tiempo. Omitir el envío no sube nada. Guardar una repetición normalmente dentro del juego sigue siendo privado.','Sì. Inviare un record richiede la conferma che il replay sarà pubblico. Il server verifica e salva la registrazione insieme al tempo. Saltare l’invio non carica nulla. Il normale salvataggio dei replay nel gioco rimane privato.'],
 'New submitted scores include public replays, available while ranked or among your five most recent verified runs on that track. Slower submitted attempts can appear in recent runs. Old private recordings are not shared retroactively. Importing an RPL cannot create a score.':['Los nuevos tiempos enviados incluyen repeticiones públicas, disponibles mientras estén clasificados o entre tus cinco carreras verificadas más recientes en esa pista. Los intentos enviados más lentos pueden aparecer en las carreras recientes. Las grabaciones privadas anteriores no se comparten retroactivamente. Importar un RPL no puede crear un récord.','I nuovi tempi inviati includono replay pubblici, disponibili finché sono in classifica o tra le tue cinque gare verificate più recenti su quella pista. I tentativi inviati più lenti possono apparire nelle gare recenti. Le vecchie registrazioni private non vengono condivise retroattivamente. Importare un RPL non può creare un record.'],
 'Public submissions have a 10-minute replay limit. Others can download a replay or add it to their game before starting, then use Options → Load Replay.':['Los envíos públicos tienen un límite de repetición de 10 minutos. Otros pueden descargar una repetición o añadirla a su juego antes de empezar y usar Options → Load Replay.','Gli invii pubblici hanno un limite di replay di 10 minuti. Gli altri possono scaricare un replay o aggiungerlo al gioco prima di avviarlo, poi usare Options → Load Replay.'],
 'Public replay consent is required to submit a high score':['Se requiere consentimiento para publicar la repetición al enviar un récord','È necessario il consenso alla pubblicazione del replay per inviare un record'],
 'Website language':['Idioma del sitio web','Lingua del sito'],
 'MANUAL':['MANUAL','MANUALE'],
 'GITHUB':['GITHUB','GITHUB'],
 'PLAY':['JUGAR','GIOCA'],
 'SETUP':['CONFIGURACIÓN','CONFIGURAZIONE'],
 'THE GAME':['EL JUEGO','IL GIOCO'],
 '3D CARS':['COCHES 3D','AUTO 3D'],
 'HIGH SCORES':['RÉCORDS','RECORD'],
 'MANUAL ↗':['MANUAL ↗','MANUALE ↗'],
 'TRACKS & REPLAYS':['CIRCUITOS Y REPETICIONES','PISTE E REPLAY'],
 'FAQ':['PREGUNTAS FRECUENTES','DOMANDE FREQUENTI'],
 'GITHUB ↗':['GITHUB ↗','GITHUB ↗'],
 'MENU':['MENÚ','MENU'],
 'Open menu':['Abrir menú','Apri menu'],
 'Close menu':['Cerrar menú','Chiudi menu'],
 'Main navigation':['Navegación principal','Navigazione principale'],
 'WELCOME TO':['BIENVENIDO A','BENVENUTO IN'],
 'Choose your car. Build your track.':['Elige tu coche. Crea tu circuito.','Scegli la tua auto. Crea la tua pista.'],
 'Take it for a drive.':['Sal a conducir.','Mettiti alla guida.'],
 'ELEVEN CARS.':['ONCE COCHES.','UNDICI AUTO.'],
 'SIX OPPONENTS.':['SEIS RIVALES.','SEI AVVERSARI.'],
 'YOUR OWN TRACKS.':['TUS PROPIOS CIRCUITOS.','LE TUE PISTE.'],
 'Read the manual':['Leer el manual','Leggi il manuale'],
 'GAME SETUP':['CONFIGURACIÓN DEL JUEGO','CONFIGURAZIONE DEL GIOCO'],
 'KEYBOARD SHORTCUTS':['ATAJOS DE TECLADO','SCORCIATOIE DA TASTIERA'],
 'Accelerate / brake':['Acelerar / frenar','Accelera / frena'],
 'Steer left / right':['Girar a izquierda / derecha','Sterza a sinistra / destra'],
 'Shift up / down':['Subir / bajar marcha','Marcia superiore / inferiore'],
 'Alternate shift keys':['Teclas alternativas para cambiar','Tasti alternativi del cambio'],
 'Open game menu':['Abrir menú del juego','Apri il menu di gioco'],
 'Cycle camera views':['Cambiar vista de cámara','Cambia visuale'],
 'Choose camera':['Elegir cámara','Scegli la visuale'],
 'Follow opponent':['Seguir al rival','Segui l’avversario'],
 'Toggle dashboard':['Mostrar / ocultar salpicadero','Mostra / nascondi cruscotto'],
 'Toggle FPS (Enhanced)':['Mostrar / ocultar FPS (mejorados)','Mostra / nascondi FPS (migliorata)'],
 'Cycle chase distance (Enhanced)':['Cambiar distancia de seguimiento (mejorados)','Cambia distanza d’inseguimento (migliorata)'],
 'Move replay camera':['Mover cámara de repetición','Sposta la camera del replay'],
 'Zoom replay camera':['Acercar / alejar cámara de repetición','Zoom della camera del replay'],
 'Choose replay control':['Elegir control de repetición','Scegli il controllo del replay'],
 'Activate replay control':['Activar control de repetición','Attiva il controllo del replay'],
 'Open terrain editor':['Abrir editor de terreno','Apri l’editor del terreno'],
 'Arrow keys':['Flechas','Tasti freccia'],
 'Arrows':['Flechas','Frecce'],
 'Space':['Espacio','Spazio'],
 'Enter':['Intro','Invio'],
 'Shift':['Mayús','Maiusc'],
 'PLAY STUNTS IN YOUR BROWSER':['JUEGA A STUNTS EN TU NAVEGADOR','GIOCA A STUNTS NEL BROWSER'],
 '3D CAR SHOWROOM':['EXPOSICIÓN DE COCHES 3D','SALONE AUTO 3D'],
 'Loading cars…':['Cargando coches…','Caricamento auto…'],
 'Restart':['Reiniciar','Riavvia'],
 'Use original graphics':['Usar gráficos originales','Usa la grafica originale'],
 'Use original music':['Usar música original','Usa la musica originale'],
 'Enable graphics update':['Activar gráficos mejorados','Attiva la grafica migliorata'],
 'Enable audio update':['Activar música mejorada','Attiva la musica aggiornata'],
 'Full screen':['Pantalla completa','Schermo intero'],
 'Exit full screen':['Salir de pantalla completa','Esci dallo schermo intero'],
 'CRT display':['Pantalla CRT','Schermo CRT'],
 'Subtle scanlines and shaded screen edges, in either graphics mode':['Líneas de barrido sutiles y bordes sombreados, en ambos modos gráficos','Linee di scansione leggere e bordi ombreggiati, in entrambe le modalità grafiche'],
 'ON':['SÍ','ON'],
 'OFF':['NO','OFF'],
 'THE ORIGINAL GAME · 1990':['EL JUEGO ORIGINAL · 1990','IL GIOCO ORIGINALE · 1990'],
 'THE STORY':['LA HISTORIA','LA STORIA'],
 'BEHIND STUNTS.':['DE STUNTS.','DI STUNTS.'],
 'Source: original manual & credits ↗':['Fuente: manual y créditos originales ↗','Fonte: manuale e crediti originali ↗'],
 'Stunts was created by Distinctive Software':['Stunts fue creado por Distinctive Software','Stunts è stato creato da Distinctive Software'],
 ', the team behind Test Drive and The Duel: Test Drive II, and published by Brøderbund in 1990. Brad Gour, Kevin Pickell, Don Mattrick and Rob Martyn designed the game. Pickell was its lead programmer, with additional programming by Rick Friesen and Gour; Martyn produced it.':[', el equipo de Test Drive y The Duel: Test Drive II, y fue publicado por Brøderbund en 1990. Brad Gour, Kevin Pickell, Don Mattrick y Rob Martyn diseñaron el juego. Pickell fue el programador principal, con programación adicional de Rick Friesen y Gour; Martyn lo produjo.',', il team di Test Drive e The Duel: Test Drive II, e pubblicato da Brøderbund nel 1990. Brad Gour, Kevin Pickell, Don Mattrick e Rob Martyn progettarono il gioco. Pickell fu il programmatore principale, con contributi di Rick Friesen e Gour; Martyn lo produsse.'],
 'The idea was to put you in charge of both the car and the course. Choose from eleven cars, race against the clock or a computer opponent, then watch your run in replay. The built-in track editor lets you create your own courses with jumps, loops and other stunt pieces.':['La idea era darte el control del coche y del circuito. Elige entre once coches, compite contra el reloj o un rival del ordenador y luego mira la repetición. El editor integrado permite crear circuitos con saltos, bucles y otras acrobacias.','L’idea era darti il controllo dell’auto e del percorso. Scegli fra undici auto, gareggia contro il tempo o un avversario controllato dal computer e poi guarda il replay. L’editor integrato permette di creare piste con salti, loop e altre acrobazie.'],
 'Its look came from Mike Smith, David Adams, Nicola Swain and Kevin Pickell, with sound by Kris Hatlelid and Michael Sokyrka.':['Los gráficos fueron obra de Mike Smith, David Adams, Nicola Swain y Kevin Pickell; el sonido, de Kris Hatlelid y Michael Sokyrka.','La grafica fu realizzata da Mike Smith, David Adams, Nicola Swain e Kevin Pickell; il sonoro da Kris Hatlelid e Michael Sokyrka.'],
 'IMPORTANT:':['IMPORTANTE:','IMPORTANTE:'],
 'When playing in updated graphics mode, please make sure to enable hardware acceleration first for best performance.':['Para obtener el mejor rendimiento con los gráficos mejorados, activa primero la aceleración por hardware.','Per le migliori prestazioni con la grafica migliorata, attiva prima l’accelerazione hardware.'],
 'Public beta':['Beta pública','Beta pubblica'],
 '· Unofficial Stunts browser reconstruction. Not an official release from the original developers or Roland.':['· Reconstrucción no oficial de Stunts para navegador. No es una versión oficial de los desarrolladores originales ni de Roland.','· Ricostruzione non ufficiale di Stunts per browser. Non è una versione ufficiale degli sviluppatori originali o di Roland.'],
 'Best played on a computer with a keyboard.':['Se recomienda jugar en un ordenador con teclado.','Si consiglia di giocare su un computer con tastiera.'],
 'Report a bug':['Informar de un error','Segnala un problema'],
 '— please include your browser, sound/display settings, and steps to reproduce it.':['— incluye el navegador, la configuración de sonido y pantalla, y los pasos para reproducirlo.','— indica il browser, le impostazioni audio e video e i passaggi per riprodurlo.'],
 'High scores are shared worldwide in the original game’s score table. Completed runs are checked against their recorded inputs; using “Continue driving” from a replay makes a run ineligible. Offline results wait in this browser until they can be submitted.':['Los récords se comparten mundialmente en la tabla original del juego. Las carreras terminadas se verifican con sus controles grabados; usar “Continue driving” desde una repetición invalida la carrera. Los resultados sin conexión esperan en este navegador hasta poder enviarse.','I record sono condivisi in tutto il mondo nella classifica originale del gioco. Le gare completate vengono verificate tramite i comandi registrati; usare “Continue driving” da un replay rende la gara non idonea. I risultati offline restano in questo browser finché possono essere inviati.'],
 'Display and sound settings':['Configuración de pantalla y sonido','Impostazioni video e audio'],
 'Open Setup':['Abrir configuración','Apri configurazione'],
 'Loading Setup…':['Cargando configuración…','Caricamento configurazione…'],
 'Exit saves · Escape cancels':['Salir guarda · Esc cancela','Esci per salvare · Esc annulla'],
 'Setup closed':['Configuración cerrada','Configurazione chiusa'],
 'Setup could not finish':['No se pudo terminar la configuración','Impossibile completare la configurazione'],
 'Saved settings are unchanged.':['La configuración guardada no ha cambiado.','Le impostazioni salvate non sono cambiate.'],
 'Saving changed settings restarts the game automatically.':['Guardar cambios reinicia el juego automáticamente.','Salvare le modifiche riavvia automaticamente il gioco.'],
 '← Back to game':['← Volver al juego','← Torna al gioco'],
 'Setup':['Configuración','Configurazione'],
 'Your saved settings apply the next time you start the game.':['La configuración guardada se aplica la próxima vez que inicies el juego.','Le impostazioni salvate si applicano al prossimo avvio del gioco.'],
 'THE SHARED LEADERBOARDS':['LAS CLASIFICACIONES COMPARTIDAS','LE CLASSIFICHE CONDIVISE'],
 'EVERY TRACK.':['CADA CIRCUITO.','OGNI PISTA.'],
 'EVERY SECOND.':['CADA SEGUNDO.','OGNI SECONDO.'],
 'The original game. A worldwide challenge.':['El juego original. Un desafío mundial.','Il gioco originale. Una sfida mondiale.'],
 'GLOBAL HIGH SCORES':['RÉCORDS MUNDIALES','RECORD MONDIALI'],
 'HIGH SCORES.':['RÉCORDS.','RECORD.'],
 'WORLDWIDE.':['MUNDIALES.','MONDIALI.'],
 'One driver. One place. Your best run deserves the spotlight.':['Un piloto. Un puesto. Tu mejor carrera merece destacar.','Un pilota. Un posto. La tua migliore gara merita di essere vista.'],
 'SET YOUR TIME':['MARCA TU TIEMPO','STABILISCI IL TUO TEMPO'],
 'TRACKS RANKED':['CIRCUITOS CLASIFICADOS','PISTE IN CLASSIFICA'],
 'BEST CAR TIMES':['MEJORES TIEMPOS POR COCHE','MIGLIORI TEMPI PER AUTO'],
 'WATCHABLE REPLAYS':['REPETICIONES DISPONIBLES','REPLAY DISPONIBILI'],
 'Overall and individual car rankings.':['Clasificación general y por coche.','Classifiche generali e per auto.'],
 'Different track contents, separate boards.':['Circuitos distintos, clasificaciones separadas.','Piste diverse, classifiche separate.'],
 'LOCAL PREVIEW · These are isolated local test scores, not the live leaderboard.':['VISTA LOCAL · Estos resultados de prueba están separados de la clasificación pública.','ANTEPRIMA LOCALE · Questi risultati di prova sono separati dalla classifica pubblica.'],
 'FIND A TRACK, DRIVER OR CAR':['BUSCAR CIRCUITO, PILOTO O COCHE','CERCA PISTA, PILOTA O AUTO'],
 'Search the leaderboards…':['Buscar en las clasificaciones…','Cerca nelle classifiche…'],
 'SORT TRACKS':['ORDENAR CIRCUITOS','ORDINA PISTE'],
 'Recently updated':['Actualizados recientemente','Aggiornati di recente'],
 'Track name A–Z':['Nombre del circuito A–Z','Nome della pista A–Z'],
 'Refresh scores':['Actualizar resultados','Aggiorna risultati'],
 'Refreshing…':['Actualizando…','Aggiornamento…'],
 'Checked {0}':['Comprobado a las {0}','Controllato alle {0}'],
 'Loading shared times…':['Cargando tiempos compartidos…','Caricamento tempi condivisi…'],
 'Not checked yet':['Sin comprobar','Non ancora controllato'],
 '· Refreshes hourly and when you return':['· Se actualiza cada hora y al volver','· Si aggiorna ogni ora e al tuo ritorno'],
 'track':['circuito','pista'],
 'tracks':['circuitos','piste'],
 'found':['encontrados','trovati'],
 'Previously loaded times are still shown.':['Se siguen mostrando los tiempos cargados antes.','I tempi caricati in precedenza restano visibili.'],
 'No matching tracks':['No hay circuitos coincidentes','Nessuna pista corrispondente'],
 'The grid is waiting.':['La parrilla te espera.','La griglia ti aspetta.'],
 'Try another track, driver or car name.':['Prueba otro nombre de circuito, piloto o coche.','Prova un altro nome di pista, pilota o auto.'],
 'Finish a qualifying race and your track’s leaderboard will appear here.':['Termina una carrera válida y la clasificación de tu circuito aparecerá aquí.','Completa una gara idonea e la classifica della pista apparirà qui.'],
 'Clear search':['Borrar búsqueda','Cancella ricerca'],
 'Let’s drive →':['A conducir →','Guidiamo →'],
 'Load more tracks (':['Cargar más circuitos (','Carica altre piste ('],
 'remaining)':['restantes)','rimanenti)'],
 'Read the scoring rules ↗':['Leer las reglas de puntuación ↗','Leggi le regole della classifica ↗'],
 'One place per named driver in each ranking. Names are grouped ignoring letter case and surrounding spaces, not verified accounts; unnamed runs remain separate. Fresh, completed races only. Replay continuation is not eligible. Common profanity is masked.':['Un puesto por piloto con nombre en cada clasificación. Los nombres se agrupan sin distinguir mayúsculas ni espacios exteriores; no son cuentas verificadas. Las carreras sin nombre permanecen separadas. Solo carreras nuevas y completas; continuar una repetición no es válido. Los insultos comunes se ocultan.','Un posto per pilota con nome in ogni classifica. I nomi vengono raggruppati ignorando maiuscole e spazi esterni; non sono account verificati. Le gare senza nome restano separate. Solo gare nuove e completate; continuare un replay non è idoneo. Le volgarità comuni vengono oscurate.'],
 'TRACK LEADERBOARD':['CLASIFICACIÓN DEL CIRCUITO','CLASSIFICA DELLA PISTA'],
 'TRACK RECORD':['RÉCORD DEL CIRCUITO','RECORD DELLA PISTA'],
 'CAR RECORD':['RÉCORD DEL COCHE','RECORD DELL’AUTO'],
 'Overall':['General','Generale'],
 'By car':['Por coche','Per auto'],
 'ALL CARS':['TODOS LOS COCHES','TUTTE LE AUTO'],
 'All accepted times, fastest first. Each run keeps its route label.':['Todos los tiempos aceptados, del más rápido al más lento. Cada carrera conserva su etiqueta de recorrido.','Tutti i tempi accettati, dal più veloce. Ogni gara mantiene la propria etichetta di percorso.'],
 'ONE PLACE PER NAMED DRIVER ·':['UN PUESTO POR PILOTO CON NOMBRE ·','UN POSTO PER PILOTA CON NOME ·'],
 '· HOVER OR TAP A NAME FOR RECENT RUNS':['· PASA EL RATÓN O TOCA UN NOMBRE PARA VER SUS ÚLTIMAS CARRERAS','· PASSA IL MOUSE O TOCCA UN NOME PER LE GARE RECENTI'],
 'DRIVER / CAR':['PILOTO / COCHE','PILOTA / AUTO'],
 'TIME':['TIEMPO','TEMPO'],
 'ROUTE / DETAILS':['RECORRIDO / DETALLES','PERCORSO / DETTAGLI'],
 'Full run':['Recorrido completo','Percorso completo'],
 'Possibly exploited':['Posible uso de exploits','Possibile exploit'],
 'Anonymous':['Anónimo','Anonimo'],
 'Run details':['Detalles de la carrera','Dettagli della gara'],
 'REPLAY':['REPETICIÓN','REPLAY'],
 'Replay ↗':['Repetición ↗','Replay ↗'],
 'No public replay':['Sin repetición pública','Nessun replay pubblico'],
 'No times yet':['Todavía no hay tiempos','Ancora nessun tempo'],
 'Finish a qualifying race to join this track’s leaderboard.':['Termina una carrera válida para entrar en la clasificación de este circuito.','Completa una gara idonea per entrare nella classifica di questa pista.'],
 '/ 7 places filled · All route categories':['/ 7 puestos ocupados · Todos los recorridos','/ 7 posti occupati · Tutti i percorsi'],
 'Track identity':['Identidad del circuito','Identità della pista'],
 'Matching file contents share this board.':['Los archivos idénticos comparten esta clasificación.','I file identici condividono questa classifica.'],
 'RECENT RUNS ·':['ÚLTIMAS CARRERAS ·','GARE RECENTI ·'],
 'Five most recent verified runs · All cars':['Las cinco últimas carreras verificadas · Todos los coches','Le cinque gare verificate più recenti · Tutte le auto'],
 'This anonymous run only':['Solo esta carrera anónima','Solo questa gara anonima'],
 'On car leaderboard':['En la clasificación del coche','In classifica per auto'],
 'Not on car leaderboard':['Fuera de la clasificación del coche','Fuori dalla classifica per auto'],
 'Up to five server-verified submissions. Older discarded attempts are unavailable. Names are not verified accounts.':['Hasta cinco carreras verificadas por el servidor. Los intentos anteriores descartados no están disponibles. Los nombres no son cuentas verificadas.','Fino a cinque gare verificate dal server. I tentativi precedenti scartati non sono disponibili. I nomi non sono account verificati.'],
 'Close recent runs':['Cerrar últimas carreras','Chiudi gare recenti'],
 'Recent runs for {0} on {1}':['Últimas carreras de {0} en {1}','Gare recenti di {0} su {1}'],
 'Recent runs are unavailable.':['Las últimas carreras no están disponibles.','Le gare recenti non sono disponibili.'],
 'YOUR NEXT RECORD STARTS HERE':['TU PRÓXIMO RÉCORD EMPIEZA AQUÍ','IL TUO PROSSIMO RECORD INIZIA QUI'],
 'Unofficial browser reconstruction · Public beta':['Reconstrucción no oficial para navegador · Beta pública','Ricostruzione non ufficiale per browser · Beta pubblica'],
 'How scoring works':['Cómo funcionan los resultados','Come funziona la classifica'],
 'Tracks, replays and save backups':['Circuitos, repeticiones y copias de seguridad','Piste, replay e copie di sicurezza'],
 'Tracks, replays and settings stay in this browser, on this website address. Clearing browser data can erase them. Download a backup to keep a copy.':['Los circuitos, las repeticiones y la configuración se guardan en este navegador y esta dirección web. Borrar los datos del navegador puede eliminarlos. Descarga una copia de seguridad para conservarlos.','Piste, replay e impostazioni restano in questo browser e a questo indirizzo web. Cancellare i dati del browser può eliminarli. Scarica una copia di sicurezza per conservarli.'],
 'Upload an original':['Sube un archivo original','Carica un file originale'],
 'track (1,802 bytes) or':['de circuito (1.802 bytes) o','di pista (1.802 byte) o'],
 'replay, then load it from the game’s track or replay menu. Files stay in this browser.':['de repetición, y cárgalo desde el menú de circuitos o repeticiones del juego. Los archivos permanecen en este navegador.','di replay, poi aprilo dal menu delle piste o dei replay nel gioco. I file restano in questo browser.'],
 'Upload track (.TRK)':['Subir circuito (.TRK)','Carica pista (.TRK)'],
 'Upload replay (.RPL)':['Subir repetición (.RPL)','Carica replay (.RPL)'],
 'Download tracks & replays':['Descargar circuitos y repeticiones','Scarica piste e replay'],
 'Download backup':['Descargar copia de seguridad','Scarica copia di sicurezza'],
 'Import backup':['Importar copia de seguridad','Importa copia di sicurezza'],
 'To import, reload this page and import before pressing Play. Save your current run first.':['Para importar, recarga esta página e importa antes de pulsar Play. Guarda primero tu carrera actual.','Per importare, ricarica la pagina e importa prima di premere Play. Salva prima la gara attuale.'],
 'Close downloads':['Cerrar descargas','Chiudi download'],
 'Close':['Cerrar','Chiudi'],
 'Download':['Descargar','Scarica'],
 'Includes bundled tracks and replays plus files you saved or uploaded. Saved versions replace bundled files with the same path and name. Download .TRK and .RPL files directly into your DOS Stunts folder. Save new tracks or runs in the game before downloading.':['Incluye los circuitos y repeticiones iniciales y tus archivos guardados o subidos. Las versiones guardadas sustituyen los archivos iniciales de igual ruta y nombre. Descarga los archivos .TRK y .RPL directamente en tu carpeta de Stunts para DOS. Guarda los circuitos o carreras nuevos en el juego antes de descargarlos.','Include piste e replay iniziali e i file salvati o caricati. Le versioni salvate sostituiscono i file iniziali con lo stesso percorso e nome. Scarica i file .TRK e .RPL direttamente nella cartella DOS di Stunts. Salva nel gioco le nuove piste o gare prima di scaricarle.'],
 'No saved tracks or replays yet. Save one in the game, then reopen this window.':['Todavía no hay circuitos ni repeticiones guardados. Guarda uno en el juego y vuelve a abrir esta ventana.','Ancora nessuna pista o replay salvato. Salvane uno nel gioco e riapri questa finestra.'],
 'bytes':['bytes','byte'],
 'Community tracks':['Circuitos de la comunidad','Piste della community'],
 'Explore tracks shared by other players. Personal imports stay private;':['Explora circuitos compartidos por otros jugadores. Los archivos importados personalmente siguen siendo privados;','Esplora piste condivise da altri giocatori. I file importati personalmente restano privati;'],
 'Share track':['Compartir circuito','Condividi pista'],
 'publishes the selected file for everyone.':['publica el archivo seleccionado para todos.','pubblica il file selezionato per tutti.'],
 'Share track (.TRK)':['Compartir circuito (.TRK)','Condividi pista (.TRK)'],
 'Refresh tracks':['Actualizar circuitos','Aggiorna piste'],
 'No community tracks yet. Share the first one.':['Todavía no hay circuitos de la comunidad. Comparte el primero.','Ancora nessuna pista della community. Condividi la prima.'],
 'Add to my game':['Añadir a mi juego','Aggiungi al mio gioco'],
 'Download .TRK':['Descargar .TRK','Scarica .TRK'],
 'More tracks':['Más circuitos','Altre piste'],
 'Reload before adding a track to your game. Save your current run first.':['Recarga antes de añadir un circuito al juego. Guarda primero tu carrera actual.','Ricarica prima di aggiungere una pista al gioco. Salva prima la gara attuale.'],
 'High-score replays':['Repeticiones de récords','Replay dei record'],
 'Watch how a shared record was driven. Verified submissions are kept privately in this browser even when they do not improve your ranking. Ranked times and your five most recent verified runs on each track can be published with':['Mira cómo se consiguió un récord compartido. Las carreras verificadas se guardan de forma privada en este navegador, aunque no mejoren tu clasificación. Los tiempos clasificados y tus cinco últimas carreras verificadas de cada circuito pueden publicarse con','Guarda come è stato ottenuto un record condiviso. Le gare verificate restano private in questo browser anche se non migliorano la tua posizione. I tempi in classifica e le tue cinque gare verificate più recenti su ogni pista possono essere pubblicati con'],
 'Share replay':['Compartir repetición','Condividi replay'],
 'Automatically share my qualifying replays':['Compartir automáticamente mis repeticiones que cumplen los requisitos','Condividi automaticamente i miei replay idonei'],
 'Off by default. Future verified qualifying recordings become public when enabled. Turning it off does not remove already shared replays.':['Desactivado por defecto. Al activarlo, las futuras grabaciones verificadas que cumplan los requisitos serán públicas. Desactivarlo no elimina las repeticiones ya compartidas.','Disattivato per impostazione predefinita. Attivandolo, le future registrazioni verificate idonee diventano pubbliche. Disattivarlo non rimuove i replay già condivisi.'],
 'Refresh replays':['Actualizar repeticiones','Aggiorna replay'],
 'Your verified runs':['Tus carreras verificadas','Le tue gare verificate'],
 'Finish a fresh race and confirm your name. Its recording appears here after server verification; it is not public until you share it.':['Termina una carrera nueva y confirma tu nombre. La grabación aparecerá aquí tras verificarse en el servidor; no será pública hasta que la compartas.','Completa una nuova gara e conferma il tuo nome. La registrazione appare qui dopo la verifica del server; resta privata finché non la condividi.'],
 'Recheck privately':['Volver a comprobar en privado','Ricontrolla in privato'],
 'Replay shared':['Repetición compartida','Replay condiviso'],
 'Shared runs':['Carreras compartidas','Gare condivise'],
 'No shared replays yet.':['Todavía no hay repeticiones compartidas.','Ancora nessun replay condiviso.'],
 'Add replay to my game':['Añadir repetición a mi juego','Aggiungi replay al mio gioco'],
 'Download .RPL':['Descargar .RPL','Scarica .RPL'],
 'Save your current run and restart the webpage game before adding a shared replay. Playback uses the original replay viewer and its camera controls.':['Guarda tu carrera actual y reinicia el juego antes de añadir una repetición compartida. Se reproduce con el visor original y sus controles de cámara.','Salva la gara attuale e riavvia il gioco prima di aggiungere un replay condiviso. La riproduzione usa il visualizzatore originale e i suoi controlli della camera.'],
 'Replays remain available while ranked or among the driver’s five most recent verified runs on that track. The latest 50 shared runs are shown.':['Las repeticiones siguen disponibles mientras estén clasificadas o entre las cinco últimas carreras verificadas del piloto en ese circuito. Se muestran las últimas 50 carreras compartidas.','I replay restano disponibili finché sono in classifica o fra le cinque gare verificate più recenti del pilota sulla pista. Vengono mostrate le ultime 50 gare condivise.'],
};
const templates=Object.entries(websiteTranslations).filter(([key])=>/\{\d+\}/.test(key)).map(([key,values])=>({regex:new RegExp('^'+key.split(/(\{\d+\})/).map(s=>/^\{\d+\}$/.test(s)?'(.+?)':s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('')+'$'),values}));
export function translateWebsite(text:string,locale:WebsiteLocale){if(locale==='en'||!text)return text;const key=text.trim(),index=locale==='es'?0:1,entry=websiteTranslations[key];let result=entry?.[index];if(!result)for(const template of templates){const match=key.match(template.regex);if(match){result=template.values[index].replace(/\{(\d+)\}/g,(_,n)=>match[Number(n)+1]);break;}}return result===undefined?text:text.slice(0,text.indexOf(key))+result+text.slice(text.indexOf(key)+key.length);}
