import {faqTranslations} from './website-faq-translations.ts';
import {statusTranslations} from './website-status-translations.ts';
export type WebsiteLocale='en'|'es'|'it';
// Each entry must include both translations. Keep keys identical to the
// English website copy; game/driver/track names are not translation keys.
export const websiteTranslations:Record<string,readonly [string,string]>={
"You confirm sharing in the submission panel; no extra browser confirmation appears.":["Confirmas la publicación en el panel de envío; no aparece ninguna confirmación adicional del navegador.","Confermi la condivisione nel pannello di invio; non appare alcuna conferma aggiuntiva del browser."],
"Track:":["Circuito:","Pista:"],
"Car:":["Coche:","Auto:"],
"RECENT RACES":["CARRERAS RECIENTES","GARE RECENTI"],
"set a new valid track record":["estableció un nuevo récord válido del circuito","ha stabilito un nuovo record valido della pista"],
"improved their time":["mejoró su tiempo","ha migliorato il proprio tempo"],
"completed a valid run":["completó una carrera válida","ha completato una gara valida"],
"submitted a run":["envió una carrera","ha inviato una gara"],
"Loading recent races…":["Cargando carreras recientes…","Caricamento delle gare recenti…"],
"Recent races are temporarily unavailable.":["Las carreras recientes no están disponibles temporalmente.","Le gare recenti non sono temporaneamente disponibili."],
"No public races yet.":["Aún no hay carreras públicas.","Non ci sono ancora gare pubbliche."],
"Show 10 more":["Mostrar 10 más","Mostra altri 10"],
"Show top 10":["Mostrar los 10 primeros","Mostra i primi 10"],
"CAR RECORDS":["RÉCORDS POR COCHE","RECORD PER AUTO"],
"Best valid time for each car · fastest first":["Mejor tiempo válido de cada coche · de más rápido a más lento","Miglior tempo valido per ogni auto · dal più veloce al più lento"],
"View ranking":["Ver clasificación","Vedi classifica"],
"Latest eight public submissions":["Los ocho últimos envíos públicos","Gli ultimi otto invii pubblici"],
"View leaderboards":["Ver clasificaciones","Vedi le classifiche"],
"VALID TRACK RECORD":["RÉCORD VÁLIDO DEL CIRCUITO","RECORD VALIDO DELLA PISTA"],
"Valid runs only, fastest first.":["Solo carreras válidas, de más rápida a más lenta.","Solo gare valide, dalla più veloce alla più lenta."],
"Runs with detected exploits, fastest first.":["Carreras con exploits detectados, de más rápida a más lenta.","Gare con exploit rilevati, dalla più veloce alla più lenta."],
"Submit your score and replay to the website leaderboard.":["Envía tu puntuación y repetición a la clasificación del sitio web.","Invia il tuo punteggio e replay alla classifica del sito web."],
"Publish my score and replay":["Publicar mi tiempo y repetición","Pubblica il mio tempo e replay"],
"Your replay will be checked automatically.":["Tu repetición se comprobará automáticamente.","Il tuo replay verrà verificato automaticamente."],
"Not now":["Ahora no","Non ora"],
"This does not change your in-game high scores.":["Esto no cambia tus mejores tiempos dentro del juego.","Questo non modifica i tuoi migliori tempi nel gioco."],
"Choose Valid or Exploit detected, then Overall or By car. Each leaderboard supports up to 100 drivers and initially shows the top 10. Use Show 10 more to expand it or Show top 10 to collapse it. Each named driver has one fastest time. The header always shows the best valid run, its driver and car. Unverified attempts remain in recent-run history. Your private in-game seven-place table is separate.":["Elige Válido o Exploit detectado, y después General o Por coche. Cada clasificación admite hasta 100 pilotos y muestra inicialmente los 10 primeros. Usa Mostrar 10 más para ampliarla o Mostrar los 10 primeros para reducirla. Cada piloto con nombre tiene un mejor tiempo. La cabecera siempre muestra la mejor carrera válida, su piloto y coche. Los intentos sin verificar permanecen en el historial reciente. Tu tabla privada del juego de siete puestos es independiente.","Scegli Valido o Exploit rilevato, poi Generale o Per auto. Ogni classifica supporta fino a 100 piloti e mostra inizialmente i primi 10. Usa Mostra altri 10 per espanderla o Mostra i primi 10 per ridurla. Ogni pilota con nome ha un tempo migliore. L’intestazione mostra sempre la migliore gara valida, il pilota e l’auto. I tentativi non verificati restano nella cronologia recente. La tua classifica privata nel gioco di sette posti è indipendente."],
"After every eligible fresh completed race, a submission panel appears over the game, including in fullscreen, whether or not your time enters the local top seven. Enter your name and submit. Publish my score and replay is checked by default; choose Not now to keep the run private. Submitting keeps you in the game. The original local name-entry flow saves only your private in-game table. Recorded inputs are verified, and slower accepted submissions can appear in your five most recent runs. Replay continuation and incomplete races are not eligible; verification limits still apply.":["Después de cada carrera nueva completada apta, aparece un panel sobre el juego, también en pantalla completa, entre o no tu tiempo en los siete mejores locales. Introduce tu nombre y envía. Publicar mi tiempo y repetición está marcado por defecto; elige Ahora no para mantener la carrera privada. Al enviar permaneces en el juego. La entrada de nombre original solo guarda tu tabla privada del juego. Se verifican los controles grabados y los envíos aceptados más lentos pueden aparecer en tus cinco carreras más recientes. No se admiten carreras incompletas ni continuadas desde una repetición; siguen aplicándose los límites de verificación.","Dopo ogni nuova gara completata idonea, appare un pannello sopra il gioco, anche a schermo intero, che il tempo entri o meno nei primi sette locali. Inserisci il nome e invia. Pubblica il mio tempo e replay è selezionato per impostazione predefinita; scegli Non ora per mantenere la gara privata. Dopo l'invio rimani nel gioco. L'inserimento del nome originale salva solo la classifica privata del gioco. I comandi registrati vengono verificati e i tempi accettati più lenti possono apparire nelle tue cinque gare più recenti. Gare incomplete e continuazioni da replay non sono ammesse; restano i limiti di verifica."],
"All runs":["Todas las carreras","Tutte le gare"],
"Run category":["Categoría de carrera","Categoria della gara"],
"/ 100 places filled":[" / 100 puestos ocupados"," / 100 posti occupati"],
"Top 100 drivers for":["Los 100 mejores pilotos de ","I 100 migliori piloti di "],
"All tracks":["Todos los circuitos","Tutte le piste"],
"All cars":["Todos los coches","Tutte le auto"],
"Car":["Coche","Auto"],
"Driver":["Piloto","Pilota"],
"Time":["Tiempo","Tempo"],
"Actions":["Acciones","Azioni"],
"Sort replays":["Ordenar repeticiones","Ordina replay"],
"Fastest first":["Más rápidos primero","Prima i più veloci"],
"Most recent":["Más recientes","Più recenti"],
"Load more replays":["Cargar más repeticiones","Carica altri replay"],
"No replays match these filters.":["Ninguna repetición coincide con estos filtros.","Nessun replay corrisponde a questi filtri."],
"Invalid replay filter":["Filtro de repetición no válido","Filtro replay non valido"],
"How can I find shared replays?":["¿Cómo encuentro repeticiones compartidas?","Come trovo i replay condivisi?"],
"The website shows up to ten drivers per track. Choose All runs, Valid, Exploit detected or Unverified, then Overall or By car. Each ranking keeps one fastest time per named driver. Your private in-game seven-place table is separate.":["El sitio muestra hasta diez pilotos por circuito. Elige Todas las carreras, Válido, Exploit detectado o Sin verificar, y después General o Por coche. Cada clasificación conserva un tiempo más rápido por piloto con nombre. Tu tabla privada del juego, de siete puestos, es independiente.","Il sito mostra fino a dieci piloti per pista. Scegli Tutte le gare, Valido, Exploit rilevato o Non verificato, poi Generale o Per auto. Ogni classifica conserva il tempo più veloce di ciascun pilota con nome. La tua classifica privata nel gioco, di sette posti, è separata."],
"Filter shared replays by track and car, then sort by fastest time or most recent. Load more to browse beyond the first 50. Ranked replays and each driver’s five most recent verified runs per track are retained. Your private in-game replays are not deleted.":["Filtra las repeticiones compartidas por circuito y coche, y ordénalas por tiempo más rápido o más recientes. Carga más para consultar más de las primeras 50. Se conservan las repeticiones clasificadas y las cinco carreras verificadas más recientes de cada piloto por circuito. Tus repeticiones privadas del juego no se eliminan.","Filtra i replay condivisi per pista e auto, poi ordinali per tempo più veloce o più recenti. Carica altri replay per vedere oltre i primi 50. Vengono conservati i replay in classifica e le cinque gare verificate più recenti di ogni pilota per pista. I tuoi replay privati nel gioco non vengono eliminati."],
 'Website high scores are separate from your private in-game table. Completed runs are checked against their recorded inputs; using “Continue driving” from a replay makes a run ineligible. Consented offline submissions wait in this browser until they can be uploaded.':['Los récords del sitio están separados de tu tabla privada del juego. Las carreras completadas se comprueban con sus entradas grabadas; usar Continuar conduciendo desde una repetición hace que la carrera no sea apta. Los envíos autorizados sin conexión esperan en este navegador hasta poder subirse.','I record del sito sono separati dalla tua tabella privata nel gioco. Le gare completate vengono controllate con gli input registrati; usare Continua a guidare da un replay rende la gara non idonea. Gli invii autorizzati offline restano in questo browser finché possono essere caricati.'],
 'Submit your completed run':['Envía tu carrera completada','Invia la tua gara completata'],
 'You do not need to beat the in-game top seven. Submitting publishes your replay for verification; only qualifying times rank, and slower verified attempts appear in recent runs.':['No necesitas superar los siete mejores tiempos del juego. El envío publica tu repetición para verificarla; solo los tiempos que clasifican aparecen en la tabla, y los intentos verificados más lentos aparecen en carreras recientes.','Non devi battere i sette migliori tempi nel gioco. L’invio pubblica il replay per la verifica; solo i tempi idonei entrano in classifica, mentre i tentativi verificati più lenti appaiono nelle gare recenti.'],
 'Driver name':['Nombre del piloto','Nome del pilota'],
 'Submit score and replay':['Enviar tiempo y repetición','Invia tempo e replay'],
 'Keep private':['Mantener privado','Mantieni privato'],
 'Enter a name using up to 16 basic characters.':['Introduce un nombre con un máximo de 16 caracteres ASCII.','Inserisci un nome con un massimo di 16 caratteri ASCII.'],
 'Could not submit this run.':['No se pudo enviar esta carrera.','Impossibile inviare questa gara.'],
 'Can I submit a run slower than the in-game top seven?':['¿Puedo enviar una carrera más lenta que los siete mejores tiempos del juego?','Posso inviare una gara più lenta dei sette migliori tempi nel gioco?'],
 'Yes. After a fresh completed race, a run that misses the local top seven gets a Submit your completed run panel beneath the game. Enter your name and choose Submit score and replay, then confirm public sharing. Qualifying local times still use the original name-entry flow. Both paths verify the recorded inputs. Slower accepted submissions appear in your five most recent runs even when they do not rank. Replay continuation and incomplete races are not eligible; recording length and verification limits still apply.':['Sí. Tras completar una carrera nueva, si no entra en los siete mejores tiempos locales, aparece Envía tu carrera completada debajo del juego. Introduce tu nombre, elige Enviar tiempo y repetición y confirma la publicación. Los tiempos que clasifican localmente siguen usando la entrada de nombre original. Ambas vías verifican las entradas grabadas. Los envíos aceptados más lentos aparecen en tus cinco carreras más recientes aunque no clasifiquen. Continuar una repetición y las carreras incompletas no son aptos; siguen aplicándose los límites de grabación y verificación.','Sì. Dopo una nuova gara completata, se il tempo non entra nei sette migliori locali, appare Invia la tua gara completata sotto il gioco. Inserisci il nome, scegli Invia tempo e replay e conferma la condivisione pubblica. I tempi idonei alla classifica locale usano ancora l’inserimento del nome originale. Entrambe le modalità verificano gli input registrati. Gli invii accettati più lenti appaiono nelle cinque gare più recenti anche se non entrano in classifica. Continuare un replay e le gare incomplete non sono idonei; restano i limiti di registrazione e verifica.'],
 'Valid means the original finish was accepted with no restricted exploit detected. Exploit detected means replay evidence identified a restricted shortcut or exploit. Unverified means there is insufficient evidence to classify the run. Hover, focus or tap the badge for a short reason. These labels do not judge the player’s intent; all accepted times remain eligible for the leaderboard.':['Válido significa que se aceptó la llegada original sin detectar un exploit restringido. Exploit detectado significa que la repetición mostró un atajo o exploit restringido. Sin verificar significa que no hay pruebas suficientes para clasificar la carrera. Pasa el cursor, enfoca o toca la etiqueta para ver una breve razón. Estas etiquetas no juzgan la intención del jugador; todos los tiempos aceptados siguen siendo aptos para la clasificación.','Valido significa che l’arrivo originale è stato accettato senza rilevare exploit vietati. Exploit rilevato significa che il replay ha mostrato una scorciatoia o un exploit vietato. Non verificato significa che le prove non bastano per classificare la gara. Passa il puntatore, seleziona con la tastiera o tocca l’etichetta per una breve motivazione. Queste etichette non giudicano l’intenzione del giocatore; tutti i tempi accettati restano idonei alla classifica.'],
 ...faqTranslations,
 ...statusTranslations,
 'Original game physics and penalties are unchanged. Valid means the original game accepted the finish and no restricted section-skipping, branch-switching or grass-speed exploit was detected. Ordinary grass driving along the same route has no time limit. Website checkpoints and driving beside a tunnel do not add extra rules. Importing an RPL does not submit a score.':['La física y las penalizaciones del juego original no cambian. Válido significa que el juego original aceptó la llegada y no se detectaron tramos saltados, cambios entre ramales ni exploits de velocidad sobre hierba restringidos. Conducir normalmente por hierba junto al mismo recorrido no tiene límite de tiempo. Los puntos de control del sitio y conducir junto a un túnel no añaden reglas. Importar un RPL no envía un tiempo.','La fisica e le penalità del gioco originale restano invariate. Valido significa che il gioco originale ha accettato l’arrivo e non sono stati rilevati salti di tratti, cambi tra rami o exploit di velocità sull’erba vietati. Guidare normalmente sull’erba lungo lo stesso percorso non ha un limite di tempo. I punti di controllo del sito e guidare accanto a un tunnel non aggiungono regole. Importare un RPL non invia un tempo.'],
 'Hover, focus or tap the badge for the recorded reason. New replay checks flag detected section-skipping, branch-switching or grass-speed exploits, not ordinary grass excursions or missed website checkpoints. Older entries without a verified retained replay can still be inconclusive. This is not a statement about the player’s intent; the score remains eligible and can be reviewed.':['Pasa el cursor, enfoca o toca la etiqueta para ver la razón registrada. Los nuevos controles de repeticiones señalan tramos saltados, cambios entre ramales o exploits de velocidad sobre hierba detectados, no salidas normales a la hierba ni puntos de control del sitio no cubiertos. Las entradas antiguas sin una repetición verificada conservada pueden seguir siendo inconcluyentes. No es una afirmación sobre la intención del jugador; el tiempo sigue siendo válido para la clasificación y puede revisarse.','Passa il puntatore, seleziona con la tastiera o tocca l’etichetta per la motivazione registrata. I nuovi controlli dei replay segnalano salti di tratti, cambi tra rami o exploit di velocità sull’erba rilevati, non normali escursioni sull’erba o punti di controllo del sito mancati. Le vecchie voci senza un replay verificato conservato possono restare inconcludenti. Non è un giudizio sull’intenzione del giocatore; il tempo rimane idoneo alla classifica e può essere riesaminato.'],
 'Original finish accepted':['Llegada aceptada por el juego original','Arrivo accettato dal gioco originale'],
 'The original game accepted this finish. No restricted section-skipping, branch-switching or grass-speed exploit was detected.':['El juego original aceptó esta llegada. No se detectaron tramos saltados, cambios entre ramales ni exploits de velocidad sobre hierba restringidos.','Il gioco originale ha accettato questo arrivo. Non sono stati rilevati salti di tratti, cambi tra rami o exploit di velocità sull’erba vietati.'],
 'Are my in-game scores separate from the website leaderboard?':['¿Mis tiempos del juego están separados de la clasificación del sitio?','I miei tempi nel gioco sono separati dalla classifica del sito?'],
 'Yes. The game keeps its own original seven-slot table for each track, including slower qualifying times under the same name. Website rankings do not replace it. Declining public sharing still saves your local score. Missing entries can be recovered automatically from verified recordings retained in the same browser when you open that track’s score table; deleted recordings cannot be recreated.':['Sí. El juego conserva su propia tabla original de siete puestos por pista, incluidos tiempos válidos más lentos con el mismo nombre. La clasificación del sitio no la reemplaza. Rechazar la publicación sigue guardando tu tiempo local. Al abrir la tabla de esa pista, las entradas que faltan pueden recuperarse automáticamente de grabaciones verificadas conservadas en el mismo navegador; las grabaciones eliminadas no pueden recrearse.','Sì. Il gioco conserva la propria tabella originale di sette posti per pista, inclusi tempi validi più lenti con lo stesso nome. La classifica del sito non la sostituisce. Rifiutare la condivisione pubblica salva comunque il tempo locale. Quando apri la tabella di quella pista, le voci mancanti possono essere recuperate automaticamente dalle registrazioni verificate conservate nello stesso browser; le registrazioni eliminate non possono essere ricreate.'],
 'Yes. Original penalties still apply. Grass excursions returning to the same road section have no time limit if you still complete the route. Skipping sections and grass-speed exploits remain flagged. Either divided-road lane and driving through the inside of loops or left/right corkscrews are allowed. Valid means a complete route was confirmed. Other runs show Possibly exploited: a shortcut was detected or full-route evidence was inconclusive. Keep your replay for review if you dispute it. Uploading an RPL does not submit a score.':['Sí. Se aplican las penalizaciones originales. Las salidas a la hierba que regresan al mismo tramo no tienen límite de tiempo si completas el recorrido. Saltarse tramos y los exploits de velocidad sobre hierba siguen señalándose. Se permiten ambos carriles de carreteras divididas y pasar por el interior de bucles o sacacorchos laterales. Recorrido completo significa que se confirmó una ruta completa. Otras carreras muestran Posible exploit: se detectó un atajo o las pruebas fueron inconcluyentes. Conserva tu repetición para solicitar una revisión. Subir un RPL no envía un tiempo.','Sì. Si applicano le penalità originali. Le escursioni sull’erba con ritorno allo stesso tratto non hanno un limite di tempo se completi il percorso. Saltare tratti e gli exploit di velocità sull’erba restano segnalati. Sono consentite entrambe le corsie delle strade divise e il passaggio all’interno di loop o corkscrew laterali. Valido significa che è stato confermato un percorso completo. Le altre gare mostrano Possibile exploit: è stata rilevata una scorciatoia o le prove erano inconcludenti. Conserva il replay per richiedere una revisione. Caricare un RPL non invia un tempo.'],
 'Tunnel passage not confirmed':['Paso por el túnel no confirmado','Passaggio nel tunnel non confermato'],
 'Road checkpoint not covered':['Punto de control de la carretera no cubierto','Punto di controllo stradale non coperto'],
 'Private — only in this browser':['Privado — solo en este navegador','Privato — solo in questo browser'],
 'Files imported here are for your own game. They are not shared with other players or synced between devices. Clearing browser data can erase them; download a backup to keep a copy.':['Los archivos importados aquí son para tu propio juego. No se comparten con otros jugadores ni se sincronizan entre dispositivos. Borrar los datos del navegador puede eliminarlos; descarga una copia de seguridad para conservarlos.','I file importati qui sono per il tuo gioco personale. Non vengono condivisi con altri giocatori né sincronizzati tra dispositivi. Cancellare i dati del browser può eliminarli; scarica una copia di sicurezza per conservarli.'],
 'Want everyone to play your track? Open':['¿Quieres que todos jueguen en tu pista? Abre','Vuoi che tutti possano giocare sulla tua pista? Apri'],
 'and choose Share track (.TRK).':['y elige Compartir circuito (.TRK).','e scegli Condividi pista (.TRK).'],
 'What do the assessment badges mean?':['¿Qué significan las etiquetas de evaluación?','Cosa significano le etichette di valutazione?'],
 'Hover, focus or tap the badge for a short assessment reason. Replay checks can identify grass transfers that skip sections, branch switching or a grass-speed exploit. Full route not confirmed means the evidence was inconclusive, not proof of cheating. The score remains eligible. Older runs without a retained public replay may only have a general explanation.':['Pasa el cursor, enfoca o toca la etiqueta para ver una breve razón de la evaluación. Los controles de la repetición pueden detectar cruces de hierba que saltan tramos, cambios entre ramales o un exploit de velocidad sobre hierba. Recorrido completo no confirmado significa que las pruebas fueron inconcluyentes, no que se haya demostrado una trampa. El tiempo sigue siendo válido para la clasificación. Las carreras antiguas sin una repetición pública conservada pueden tener solo una explicación general.','Passa il puntatore, seleziona con la tastiera o tocca l’etichetta per una breve motivazione. I controlli del replay possono rilevare attraversamenti dell’erba che saltano tratti, cambi tra rami o un exploit di velocità sull’erba. Percorso completo non confermato significa che le prove sono inconcludenti, non che sia stato dimostrato un imbroglio. Il tempo rimane idoneo alla classifica. Le vecchie gare senza un replay pubblico conservato possono avere solo una spiegazione generale.'],
 'Full route confirmed':['Recorrido completo confirmado','Percorso completo confermato'],
 'Grass-speed exploit':['Exploit de velocidad sobre hierba','Exploit di velocità sull’erba'],
 'Switched route branches':['Cambio entre ramales del recorrido','Cambio tra rami del percorso'],
 'Crossed grass to skip sections':['Cruzó hierba para saltar tramos','Attraversamento dell’erba per saltare tratti'],
 'Shortcut or exploit detected':['Atajo o exploit detectado','Scorciatoia o exploit rilevato'],
 'Grass-speed evidence inconclusive':['Pruebas de velocidad sobre hierba inconcluyentes','Prove di velocità sull’erba inconcludenti'],
 'Full route not confirmed':['Recorrido completo no confirmado','Percorso completo non confermato'],
 'Submission saved in this browser. Verification continues in the background.':['Envío guardado en este navegador. La verificación continúa en segundo plano.','Invio salvato in questo browser. La verifica continua in background.'],
 'The leaderboard keeps your best qualifying time. Your five most recent verified submissions can appear in recent runs with their public replays, including slower attempts. Valid is an assessed category, not a selectable racing mode.':['La clasificación conserva tu mejor tiempo válido. Tus cinco envíos verificados más recientes pueden aparecer con sus repeticiones públicas, incluidos los intentos más lentos. Válido es una categoría evaluada, no un modo seleccionable.','La classifica conserva il tuo miglior tempo valido. I tuoi cinque invii verificati più recenti possono apparire con i replay pubblici, inclusi i tentativi più lenti. Valido è una categoria valutata, non una modalità selezionabile.'],
 'Submitting your high score also publishes your replay. Continue?':['Enviar tu récord también publica tu repetición. ¿Continuar?','Inviare il tuo record pubblica anche il replay. Continuare?'],
 'Run verified. Its replay is public while ranked or among your five most recent verified runs.':['Carrera verificada. Su repetición es pública mientras esté clasificada o entre tus cinco carreras verificadas más recientes.','Gara verificata. Il replay è pubblico finché è in classifica o tra le tue cinque gare verificate più recenti.'],
 'High-score submission cancelled. Nothing was uploaded.':['Envío del récord cancelado. No se ha subido nada.','Invio del record annullato. Non è stato caricato nulla.'],
 'Submitting a high score also publishes its verified replay. Skip submission to keep the run private. Older private recordings are not published automatically.':['Enviar un récord también publica su repetición verificada. Omite el envío para mantener la carrera privada. Las grabaciones privadas anteriores no se publican automáticamente.','Inviare un record pubblica anche il replay verificato. Salta l’invio per mantenere privata la gara. Le vecchie registrazioni private non vengono pubblicate automaticamente.'],
 'Finish a fresh race and confirm public replay sharing when submitting your score. The verified recording appears here and is published automatically.':['Completa una nueva carrera y confirma la publicación de la repetición al enviar tu tiempo. La grabación verificada aparece aquí y se publica automáticamente.','Completa una nuova gara e conferma la condivisione pubblica del replay quando invii il tempo. La registrazione verificata appare qui e viene pubblicata automaticamente.'],
 'Are replays required for high scores?':['¿Se requieren repeticiones para los récords?','I replay sono obbligatori per i record?'],
 'Yes. Submitting a high score requires confirmation that its replay will be public. The server verifies and stores the recording with the score. Skipping submission uploads nothing. Ordinary in-game replay saving stays private.':['Sí. Enviar un récord requiere confirmar que su repetición será pública. El servidor verifica y guarda la grabación junto con el tiempo. Omitir el envío no sube nada. Guardar una repetición normalmente dentro del juego sigue siendo privado.','Sì. Inviare un record richiede la conferma che il replay sarà pubblico. Il server verifica e salva la registrazione insieme al tempo. Saltare l’invio non carica nulla. Il normale salvataggio dei replay nel gioco rimane privato.'],
 'New submitted scores include public replays, available while ranked or among your five most recent verified runs on that track. Slower submitted attempts can appear in recent runs. Old private recordings are not shared retroactively. Importing an RPL cannot create a score.':['Los nuevos tiempos enviados incluyen repeticiones públicas, disponibles mientras estén clasificados o entre tus cinco carreras verificadas más recientes en esa pista. Los intentos enviados más lentos pueden aparecer en las carreras recientes. Las grabaciones privadas anteriores no se comparten retroactivamente. Importar un RPL no puede crear un récord.','I nuovi tempi inviati includono replay pubblici, disponibili finché sono in classifica o tra le tue cinque gare verificate più recenti su quella pista. I tentativi inviati più lenti possono apparire nelle gare recenti. Le vecchie registrazioni private non vengono condivise retroattivamente. Importare un RPL non può creare un record.'],
 'Public submissions have a 10-minute replay limit. Others can download a replay or add it to their game before starting, then use Options → Load Replay.':['Los envíos públicos tienen un límite de repetición de 10 minutos. Otros pueden descargar una repetición o añadirla a su juego antes de empezar y usar Options → Load Replay.','Gli invii pubblici hanno un limite di replay di 10 minuti. Gli altri possono scaricare un replay o aggiungerlo al gioco prima di avviarlo, poi usare Options → Load Replay.'],
 'Public replay consent is required to submit a high score':['Se requiere consentimiento para publicar la repetición al enviar un récord','È necessario il consenso alla pubblicazione del replay per inviare un record'],
 'Website language':['Idioma del sitio web','Lingua del sito'],
 'MANUAL':['MANUAL','MANUALE'],
 'GITHUB':['GITHUB','GITHUB'],
 'PLAY':['JUGAR','GIOCA'],
 'SETUP':['CONFIGURACIÓN','CONFIGURAZIONE'],
 'THE GAME':['EL JUEGO','IL GIOCO'],
 '3D CARS':['COCHES 3D','AUTO 3D'],
 'HIGH SCORES':['RÉCORDS','RECORD'],
 'MANUAL ↗':['MANUAL ↗','MANUALE ↗'],
 'TRACKS & REPLAYS':['CIRCUITOS Y REPETICIONES','PISTE E REPLAY'],
 'FAQ':['PREGUNTAS FRECUENTES','DOMANDE FREQUENTI'],
 'GITHUB ↗':['GITHUB ↗','GITHUB ↗'],
 'MENU':['MENÚ','MENU'],
 'Open menu':['Abrir menú','Apri menu'],
 'Close menu':['Cerrar menú','Chiudi menu'],
 'Main navigation':['Navegación principal','Navigazione principale'],
 'WELCOME TO':['BIENVENIDO A','BENVENUTO IN'],
 'Choose your car. Build your track.':['Elige tu coche. Crea tu circuito.','Scegli la tua auto. Crea la tua pista.'],
 'Take it for a drive.':['Sal a conducir.','Mettiti alla guida.'],
 'ELEVEN CARS.':['ONCE COCHES.','UNDICI AUTO.'],
 'SIX OPPONENTS.':['SEIS RIVALES.','SEI AVVERSARI.'],
 'YOUR OWN TRACKS.':['TUS PROPIOS CIRCUITOS.','LE TUE PISTE.'],
 'Read the manual':['Leer el manual','Leggi il manuale'],
 'GAME SETUP':['CONFIGURACIÓN DEL JUEGO','CONFIGURAZIONE DEL GIOCO'],
 'KEYBOARD SHORTCUTS':['ATAJOS DE TECLADO','SCORCIATOIE DA TASTIERA'],
 'Accelerate / brake':['Acelerar / frenar','Accelera / frena'],
 'Steer left / right':['Girar a izquierda / derecha','Sterza a sinistra / destra'],
 'Shift up / down':['Subir / bajar marcha','Marcia superiore / inferiore'],
 'Alternate shift keys':['Teclas alternativas para cambiar','Tasti alternativi del cambio'],
 'Open game menu':['Abrir menú del juego','Apri il menu di gioco'],
 'Cycle camera views':['Cambiar vista de cámara','Cambia visuale'],
 'Choose camera':['Elegir cámara','Scegli la visuale'],
 'Follow opponent':['Seguir al rival','Segui l’avversario'],
 'Toggle dashboard':['Mostrar / ocultar salpicadero','Mostra / nascondi cruscotto'],
 'Toggle FPS (Enhanced)':['Mostrar / ocultar FPS (mejorados)','Mostra / nascondi FPS (migliorata)'],
 'Cycle chase distance (Enhanced)':['Cambiar distancia de seguimiento (mejorados)','Cambia distanza d’inseguimento (migliorata)'],
 'Move replay camera':['Mover cámara de repetición','Sposta la camera del replay'],
 'Zoom replay camera':['Acercar / alejar cámara de repetición','Zoom della camera del replay'],
 'Choose replay control':['Elegir control de repetición','Scegli il controllo del replay'],
 'Activate replay control':['Activar control de repetición','Attiva il controllo del replay'],
 'Open terrain editor':['Abrir editor de terreno','Apri l’editor del terreno'],
 'Arrow keys':['Flechas','Tasti freccia'],
 'Arrows':['Flechas','Frecce'],
 'Space':['Espacio','Spazio'],
 'Enter':['Intro','Invio'],
 'Shift':['Mayús','Maiusc'],
 'PLAY STUNTS IN YOUR BROWSER':['JUEGA A STUNTS EN TU NAVEGADOR','GIOCA A STUNTS NEL BROWSER'],
 '3D CAR SHOWROOM':['EXPOSICIÓN DE COCHES 3D','SALONE AUTO 3D'],
 'Loading cars…':['Cargando coches…','Caricamento auto…'],
 'Restart':['Reiniciar','Riavvia'],
 'Use original graphics':['Usar gráficos originales','Usa la grafica originale'],
 'Use original music':['Usar música original','Usa la musica originale'],
 'Enable graphics update':['Activar gráficos mejorados','Attiva la grafica migliorata'],
 'Enable audio update':['Activar música mejorada','Attiva la musica aggiornata'],
 'Full screen':['Pantalla completa','Schermo intero'],
 'Exit full screen':['Salir de pantalla completa','Esci dallo schermo intero'],
 'CRT display':['Pantalla CRT','Schermo CRT'],
 'Subtle scanlines and shaded screen edges, in either graphics mode':['Líneas de barrido sutiles y bordes sombreados, en ambos modos gráficos','Linee di scansione leggere e bordi ombreggiati, in entrambe le modalità grafiche'],
 'ON':['SÍ','ON'],
 'OFF':['NO','OFF'],
 'THE ORIGINAL GAME · 1990':['EL JUEGO ORIGINAL · 1990','IL GIOCO ORIGINALE · 1990'],
 'THE STORY':['LA HISTORIA','LA STORIA'],
 'BEHIND STUNTS.':['DE STUNTS.','DI STUNTS.'],
 'Source: original manual & credits ↗':['Fuente: manual y créditos originales ↗','Fonte: manuale e crediti originali ↗'],
 'Stunts was created by Distinctive Software':['Stunts fue creado por Distinctive Software','Stunts è stato creato da Distinctive Software'],
 ', the team behind Test Drive and The Duel: Test Drive II, and published by Brøderbund in 1990. Brad Gour, Kevin Pickell, Don Mattrick and Rob Martyn designed the game. Pickell was its lead programmer, with additional programming by Rick Friesen and Gour; Martyn produced it.':[', el equipo de Test Drive y The Duel: Test Drive II, y fue publicado por Brøderbund en 1990. Brad Gour, Kevin Pickell, Don Mattrick y Rob Martyn diseñaron el juego. Pickell fue el programador principal, con programación adicional de Rick Friesen y Gour; Martyn lo produjo.',', il team di Test Drive e The Duel: Test Drive II, e pubblicato da Brøderbund nel 1990. Brad Gour, Kevin Pickell, Don Mattrick e Rob Martyn progettarono il gioco. Pickell fu il programmatore principale, con contributi di Rick Friesen e Gour; Martyn lo produsse.'],
 'The idea was to put you in charge of both the car and the course. Choose from eleven cars, race against the clock or a computer opponent, then watch your run in replay. The built-in track editor lets you create your own courses with jumps, loops and other stunt pieces.':['La idea era darte el control del coche y del circuito. Elige entre once coches, compite contra el reloj o un rival del ordenador y luego mira la repetición. El editor integrado permite crear circuitos con saltos, bucles y otras acrobacias.','L’idea era darti il controllo dell’auto e del percorso. Scegli fra undici auto, gareggia contro il tempo o un avversario controllato dal computer e poi guarda il replay. L’editor integrato permette di creare piste con salti, loop e altre acrobazie.'],
 'Its look came from Mike Smith, David Adams, Nicola Swain and Kevin Pickell, with sound by Kris Hatlelid and Michael Sokyrka.':['Los gráficos fueron obra de Mike Smith, David Adams, Nicola Swain y Kevin Pickell; el sonido, de Kris Hatlelid y Michael Sokyrka.','La grafica fu realizzata da Mike Smith, David Adams, Nicola Swain e Kevin Pickell; il sonoro da Kris Hatlelid e Michael Sokyrka.'],
 'IMPORTANT:':['IMPORTANTE:','IMPORTANTE:'],
 'When playing in updated graphics mode, please make sure to enable hardware acceleration first for best performance.':['Para obtener el mejor rendimiento con los gráficos mejorados, activa primero la aceleración por hardware.','Per le migliori prestazioni con la grafica migliorata, attiva prima l’accelerazione hardware.'],
 'Public beta':['Beta pública','Beta pubblica'],
 '· Unofficial Stunts browser reconstruction. Not an official release from the original developers or Roland.':['· Reconstrucción no oficial de Stunts para navegador. No es una versión oficial de los desarrolladores originales ni de Roland.','· Ricostruzione non ufficiale di Stunts per browser. Non è una versione ufficiale degli sviluppatori originali o di Roland.'],
 'Best played on a computer with a keyboard.':['Se recomienda jugar en un ordenador con teclado.','Si consiglia di giocare su un computer con tastiera.'],
 'Report a bug':['Informar de un error','Segnala un problema'],
 '— please include your browser, sound/display settings, and steps to reproduce it.':['— incluye el navegador, la configuración de sonido y pantalla, y los pasos para reproducirlo.','— indica il browser, le impostazioni audio e video e i passaggi per riprodurlo.'],
 'High scores are shared worldwide in the original game’s score table. Completed runs are checked against their recorded inputs; using “Continue driving” from a replay makes a run ineligible. Offline results wait in this browser until they can be submitted.':['Los récords se comparten mundialmente en la tabla original del juego. Las carreras terminadas se verifican con sus controles grabados; usar “Continue driving” desde una repetición invalida la carrera. Los resultados sin conexión esperan en este navegador hasta poder enviarse.','I record sono condivisi in tutto il mondo nella classifica originale del gioco. Le gare completate vengono verificate tramite i comandi registrati; usare “Continue driving” da un replay rende la gara non idonea. I risultati offline restano in questo browser finché possono essere inviati.'],
 'Display and sound settings':['Configuración de pantalla y sonido','Impostazioni video e audio'],
 'Open Setup':['Abrir configuración','Apri configurazione'],
 'Loading Setup…':['Cargando configuración…','Caricamento configurazione…'],
 'Exit saves · Escape cancels':['Salir guarda · Esc cancela','Esci per salvare · Esc annulla'],
 'Setup closed':['Configuración cerrada','Configurazione chiusa'],
 'Setup could not finish':['No se pudo terminar la configuración','Impossibile completare la configurazione'],
 'Saved settings are unchanged.':['La configuración guardada no ha cambiado.','Le impostazioni salvate non sono cambiate.'],
 'Saving changed settings restarts the game automatically.':['Guardar cambios reinicia el juego automáticamente.','Salvare le modifiche riavvia automaticamente il gioco.'],
 '← Back to game':['← Volver al juego','← Torna al gioco'],
 'Setup':['Configuración','Configurazione'],
 'Your saved settings apply the next time you start the game.':['La configuración guardada se aplica la próxima vez que inicies el juego.','Le impostazioni salvate si applicano al prossimo avvio del gioco.'],
 'THE SHARED LEADERBOARDS':['LAS CLASIFICACIONES COMPARTIDAS','LE CLASSIFICHE CONDIVISE'],
 'EVERY TRACK.':['CADA CIRCUITO.','OGNI PISTA.'],
 'EVERY SECOND.':['CADA SEGUNDO.','OGNI SECONDO.'],
 'The original game. A worldwide challenge.':['El juego original. Un desafío mundial.','Il gioco originale. Una sfida mondiale.'],
 'GLOBAL HIGH SCORES':['RÉCORDS MUNDIALES','RECORD MONDIALI'],
 'HIGH SCORES.':['RÉCORDS.','RECORD.'],
 'WORLDWIDE.':['MUNDIALES.','MONDIALI.'],
 'One driver. One place. Your best run deserves the spotlight.':['Un piloto. Un puesto. Tu mejor carrera merece destacar.','Un pilota. Un posto. La tua migliore gara merita di essere vista.'],
 'SET YOUR TIME':['MARCA TU TIEMPO','STABILISCI IL TUO TEMPO'],
 'TRACKS RANKED':['CIRCUITOS CLASIFICADOS','PISTE IN CLASSIFICA'],
 'BEST CAR TIMES':['MEJORES TIEMPOS POR COCHE','MIGLIORI TEMPI PER AUTO'],
 'WATCHABLE REPLAYS':['REPETICIONES DISPONIBLES','REPLAY DISPONIBILI'],
 'Overall and individual car rankings.':['Clasificación general y por coche.','Classifiche generali e per auto.'],
 'Different track contents, separate boards.':['Circuitos distintos, clasificaciones separadas.','Piste diverse, classifiche separate.'],
 'LOCAL PREVIEW · These are isolated local test scores, not the live leaderboard.':['VISTA LOCAL · Estos resultados de prueba están separados de la clasificación pública.','ANTEPRIMA LOCALE · Questi risultati di prova sono separati dalla classifica pubblica.'],
 'FIND A TRACK, DRIVER OR CAR':['BUSCAR CIRCUITO, PILOTO O COCHE','CERCA PISTA, PILOTA O AUTO'],
 'Search the leaderboards…':['Buscar en las clasificaciones…','Cerca nelle classifiche…'],
 'SORT TRACKS':['ORDENAR CIRCUITOS','ORDINA PISTE'],
 'Recently updated':['Actualizados recientemente','Aggiornati di recente'],
 'Track name A–Z':['Nombre del circuito A–Z','Nome della pista A–Z'],
 'Refresh scores':['Actualizar resultados','Aggiorna risultati'],
 'Refreshing…':['Actualizando…','Aggiornamento…'],
 'Checked {0}':['Comprobado a las {0}','Controllato alle {0}'],
 'Updated {0}':['Actualizado a las {0}','Aggiornato alle {0}'],
 'Loading shared times…':['Cargando tiempos compartidos…','Caricamento tempi condivisi…'],
 'Not checked yet':['Sin comprobar','Non ancora controllato'],
 '· Refreshes hourly and when you return':['· Se actualiza cada hora y al volver','· Si aggiorna ogni ora e al tuo ritorno'],
 'track':['circuito','pista'],
 'tracks':['circuitos','piste'],
 'found':['encontrados','trovati'],
 'Previously loaded times are still shown.':['Se siguen mostrando los tiempos cargados antes.','I tempi caricati in precedenza restano visibili.'],
 'No matching tracks':['No hay circuitos coincidentes','Nessuna pista corrispondente'],
 'The grid is waiting.':['La parrilla te espera.','La griglia ti aspetta.'],
 'Try another track, driver or car name.':['Prueba otro nombre de circuito, piloto o coche.','Prova un altro nome di pista, pilota o auto.'],
 'Finish a qualifying race and your track’s leaderboard will appear here.':['Termina una carrera válida y la clasificación de tu circuito aparecerá aquí.','Completa una gara idonea e la classifica della pista apparirà qui.'],
 'Clear search':['Borrar búsqueda','Cancella ricerca'],
 'Let’s drive →':['A conducir →','Guidiamo →'],
 'Load more tracks (':['Cargar más circuitos (','Carica altre piste ('],
 'remaining)':['restantes)','rimanenti)'],
 'Read the scoring rules ↗':['Leer las reglas de puntuación ↗','Leggi le regole della classifica ↗'],
 'One place per named driver in each ranking. Names are grouped ignoring letter case and surrounding spaces, not verified accounts; unnamed runs remain separate. Fresh, completed races only. Replay continuation is not eligible. Common profanity is masked.':['Un puesto por piloto con nombre en cada clasificación. Los nombres se agrupan sin distinguir mayúsculas ni espacios exteriores; no son cuentas verificadas. Las carreras sin nombre permanecen separadas. Solo carreras nuevas y completas; continuar una repetición no es válido. Los insultos comunes se ocultan.','Un posto per pilota con nome in ogni classifica. I nomi vengono raggruppati ignorando maiuscole e spazi esterni; non sono account verificati. Le gare senza nome restano separate. Solo gare nuove e completate; continuare un replay non è idoneo. Le volgarità comuni vengono oscurate.'],
 'TRACK LEADERBOARD':['CLASIFICACIÓN DEL CIRCUITO','CLASSIFICA DELLA PISTA'],
 'TRACK RECORD':['RÉCORD DEL CIRCUITO','RECORD DELLA PISTA'],
 'CAR RECORD':['RÉCORD DEL COCHE','RECORD DELL’AUTO'],
 'Overall':['General','Generale'],
 'By car':['Por coche','Per auto'],
 'ALL CARS':['TODOS LOS COCHES','TUTTE LE AUTO'],
 'All accepted times, fastest first. Each run keeps its route label.':['Todos los tiempos aceptados, del más rápido al más lento. Cada carrera conserva su etiqueta de recorrido.','Tutti i tempi accettati, dal più veloce. Ogni gara mantiene la propria etichetta di percorso.'],
 'ONE PLACE PER NAMED DRIVER ·':['UN PUESTO POR PILOTO CON NOMBRE ·','UN POSTO PER PILOTA CON NOME ·'],
 '· HOVER OR TAP A NAME FOR RECENT RUNS':['· PASA EL RATÓN O TOCA UN NOMBRE PARA VER SUS ÚLTIMAS CARRERAS','· PASSA IL MOUSE O TOCCA UN NOME PER LE GARE RECENTI'],
 'DRIVER / CAR':['PILOTO / COCHE','PILOTA / AUTO'],
 'TIME':['TIEMPO','TEMPO'],
 'ROUTE / DETAILS':['RECORRIDO / DETALLES','PERCORSO / DETTAGLI'],
 'Valid':['Válido','Valido'],
 'Exploit detected':['Exploit detectado','Exploit rilevato'],
 'Unverified':['Sin verificar','Non verificato'],
 'Anonymous':['Anónimo','Anonimo'],
 'Run details':['Detalles de la carrera','Dettagli della gara'],
 'REPLAY':['REPETICIÓN','REPLAY'],
 'Replay ↗':['Repetición ↗','Replay ↗'],
 'No public replay':['Sin repetición pública','Nessun replay pubblico'],
 'No times yet':['Todavía no hay tiempos','Ancora nessun tempo'],
 'Finish a qualifying race to join this track’s leaderboard.':['Termina una carrera válida para entrar en la clasificación de este circuito.','Completa una gara idonea per entrare nella classifica di questa pista.'],
 '/ 7 places filled · All route categories':['/ 7 puestos ocupados · Todos los recorridos','/ 7 posti occupati · Tutti i percorsi'],
 'Track identity':['Identidad del circuito','Identità della pista'],
 'Matching file contents share this board.':['Los archivos idénticos comparten esta clasificación.','I file identici condividono questa classifica.'],
 'RECENT RUNS ·':['ÚLTIMAS CARRERAS ·','GARE RECENTI ·'],
 'Five most recent verified runs · All cars':['Las cinco últimas carreras verificadas · Todos los coches','Le cinque gare verificate più recenti · Tutte le auto'],
 'This anonymous run only':['Solo esta carrera anónima','Solo questa gara anonima'],
 'On car leaderboard':['En la clasificación del coche','In classifica per auto'],
 'Not on car leaderboard':['Fuera de la clasificación del coche','Fuori dalla classifica per auto'],
 'Up to five server-verified submissions. Older discarded attempts are unavailable. Names are not verified accounts.':['Hasta cinco carreras verificadas por el servidor. Los intentos anteriores descartados no están disponibles. Los nombres no son cuentas verificadas.','Fino a cinque gare verificate dal server. I tentativi precedenti scartati non sono disponibili. I nomi non sono account verificati.'],
 'Close recent runs':['Cerrar últimas carreras','Chiudi gare recenti'],
 'Recent runs for {0} on {1}':['Últimas carreras de {0} en {1}','Gare recenti di {0} su {1}'],
 'Recent runs are unavailable.':['Las últimas carreras no están disponibles.','Le gare recenti non sono disponibili.'],
 'YOUR NEXT RECORD STARTS HERE':['TU PRÓXIMO RÉCORD EMPIEZA AQUÍ','IL TUO PROSSIMO RECORD INIZIA QUI'],
 'Unofficial browser reconstruction · Public beta':['Reconstrucción no oficial para navegador · Beta pública','Ricostruzione non ufficiale per browser · Beta pubblica'],
 'How scoring works':['Cómo funcionan los resultados','Come funziona la classifica'],
 'Tracks, replays and save backups':['Circuitos, repeticiones y copias de seguridad','Piste, replay e copie di sicurezza'],
 'Tracks, replays and settings stay in this browser, on this website address. Clearing browser data can erase them. Download a backup to keep a copy.':['Los circuitos, las repeticiones y la configuración se guardan en este navegador y esta dirección web. Borrar los datos del navegador puede eliminarlos. Descarga una copia de seguridad para conservarlos.','Piste, replay e impostazioni restano in questo browser e a questo indirizzo web. Cancellare i dati del browser può eliminarli. Scarica una copia di sicurezza per conservarli.'],
 'Upload an original':['Sube un archivo original','Carica un file originale'],
 'track (1,802 bytes) or':['de circuito (1.802 bytes) o','di pista (1.802 byte) o'],
 'replay, then load it from the game’s track or replay menu. Files stay in this browser.':['de repetición, y cárgalo desde el menú de circuitos o repeticiones del juego. Los archivos permanecen en este navegador.','di replay, poi aprilo dal menu delle piste o dei replay nel gioco. I file restano in questo browser.'],
 'Upload track (.TRK)':['Subir circuito (.TRK)','Carica pista (.TRK)'],
 'Upload replay (.RPL)':['Subir repetición (.RPL)','Carica replay (.RPL)'],
 'Download tracks & replays':['Descargar circuitos y repeticiones','Scarica piste e replay'],
 'Download backup':['Descargar copia de seguridad','Scarica copia di sicurezza'],
 'Import backup':['Importar copia de seguridad','Importa copia di sicurezza'],
 'To import, reload this page and import before pressing Play. Save your current run first.':['Para importar, recarga esta página e importa antes de pulsar Play. Guarda primero tu carrera actual.','Per importare, ricarica la pagina e importa prima di premere Play. Salva prima la gara attuale.'],
 'Close downloads':['Cerrar descargas','Chiudi download'],
 'Close':['Cerrar','Chiudi'],
 'Download':['Descargar','Scarica'],
 'Includes bundled tracks and replays plus files you saved or uploaded. Saved versions replace bundled files with the same path and name. Download .TRK and .RPL files directly into your DOS Stunts folder. Save new tracks or runs in the game before downloading.':['Incluye los circuitos y repeticiones iniciales y tus archivos guardados o subidos. Las versiones guardadas sustituyen los archivos iniciales de igual ruta y nombre. Descarga los archivos .TRK y .RPL directamente en tu carpeta de Stunts para DOS. Guarda los circuitos o carreras nuevos en el juego antes de descargarlos.','Include piste e replay iniziali e i file salvati o caricati. Le versioni salvate sostituiscono i file iniziali con lo stesso percorso e nome. Scarica i file .TRK e .RPL direttamente nella cartella DOS di Stunts. Salva nel gioco le nuove piste o gare prima di scaricarle.'],
 'No saved tracks or replays yet. Save one in the game, then reopen this window.':['Todavía no hay circuitos ni repeticiones guardados. Guarda uno en el juego y vuelve a abrir esta ventana.','Ancora nessuna pista o replay salvato. Salvane uno nel gioco e riapri questa finestra.'],
 'bytes':['bytes','byte'],
 'Community tracks':['Circuitos de la comunidad','Piste della community'],
 'Explore tracks shared by other players. Personal imports stay private;':['Explora circuitos compartidos por otros jugadores. Los archivos importados personalmente siguen siendo privados;','Esplora piste condivise da altri giocatori. I file importati personalmente restano privati;'],
 'Share track':['Compartir circuito','Condividi pista'],
 'publishes the selected file for everyone.':['publica el archivo seleccionado para todos.','pubblica il file selezionato per tutti.'],
 'Share track (.TRK)':['Compartir circuito (.TRK)','Condividi pista (.TRK)'],
 'Refresh tracks':['Actualizar circuitos','Aggiorna piste'],
 'No community tracks yet. Share the first one.':['Todavía no hay circuitos de la comunidad. Comparte el primero.','Ancora nessuna pista della community. Condividi la prima.'],
 'Add to my game':['Añadir a mi juego','Aggiungi al mio gioco'],
 'Download .TRK':['Descargar .TRK','Scarica .TRK'],
 'More tracks':['Más circuitos','Altre piste'],
 'Reload before adding a track to your game. Save your current run first.':['Recarga antes de añadir un circuito al juego. Guarda primero tu carrera actual.','Ricarica prima di aggiungere una pista al gioco. Salva prima la gara attuale.'],
 'High-score replays':['Repeticiones de récords','Replay dei record'],
 'Watch how a shared record was driven. Verified submissions are kept privately in this browser even when they do not improve your ranking. Ranked times and your five most recent verified runs on each track can be published with':['Mira cómo se consiguió un récord compartido. Las carreras verificadas se guardan de forma privada en este navegador, aunque no mejoren tu clasificación. Los tiempos clasificados y tus cinco últimas carreras verificadas de cada circuito pueden publicarse con','Guarda come è stato ottenuto un record condiviso. Le gare verificate restano private in questo browser anche se non migliorano la tua posizione. I tempi in classifica e le tue cinque gare verificate più recenti su ogni pista possono essere pubblicati con'],
 'Share replay':['Compartir repetición','Condividi replay'],
 'Automatically share my qualifying replays':['Compartir automáticamente mis repeticiones que cumplen los requisitos','Condividi automaticamente i miei replay idonei'],
 'Off by default. Future verified qualifying recordings become public when enabled. Turning it off does not remove already shared replays.':['Desactivado por defecto. Al activarlo, las futuras grabaciones verificadas que cumplan los requisitos serán públicas. Desactivarlo no elimina las repeticiones ya compartidas.','Disattivato per impostazione predefinita. Attivandolo, le future registrazioni verificate idonee diventano pubbliche. Disattivarlo non rimuove i replay già condivisi.'],
 'Refresh replays':['Actualizar repeticiones','Aggiorna replay'],
 'Your verified runs':['Tus carreras verificadas','Le tue gare verificate'],
 'Finish a fresh race and confirm your name. Its recording appears here after server verification; it is not public until you share it.':['Termina una carrera nueva y confirma tu nombre. La grabación aparecerá aquí tras verificarse en el servidor; no será pública hasta que la compartas.','Completa una nuova gara e conferma il tuo nome. La registrazione appare qui dopo la verifica del server; resta privata finché non la condividi.'],
 'Recheck privately':['Volver a comprobar en privado','Ricontrolla in privato'],
 'Replay shared':['Repetición compartida','Replay condiviso'],
 'Shared runs':['Carreras compartidas','Gare condivise'],
 'No shared replays yet.':['Todavía no hay repeticiones compartidas.','Ancora nessun replay condiviso.'],
 'Add replay to my game':['Añadir repetición a mi juego','Aggiungi replay al mio gioco'],
 'Download .RPL':['Descargar .RPL','Scarica .RPL'],
 'Save your current run and restart the webpage game before adding a shared replay. Playback uses the original replay viewer and its camera controls.':['Guarda tu carrera actual y reinicia el juego antes de añadir una repetición compartida. Se reproduce con el visor original y sus controles de cámara.','Salva la gara attuale e riavvia il gioco prima di aggiungere un replay condiviso. La riproduzione usa il visualizzatore originale e i suoi controlli della camera.'],
 'Replays remain available while ranked or among the driver’s five most recent verified runs on that track. The latest 50 shared runs are shown.':['Las repeticiones siguen disponibles mientras estén clasificadas o entre las cinco últimas carreras verificadas del piloto en ese circuito. Se muestran las últimas 50 carreras compartidas.','I replay restano disponibili finché sono in classifica o fra le cinque gare verificate più recenti del pilota sulla pista. Vengono mostrate le ultime 50 gare condivise.'],
};
const templates=Object.entries(websiteTranslations).filter(([key])=>/\{\d+\}/.test(key)).map(([key,values])=>({regex:new RegExp('^'+key.split(/(\{\d+\})/).map(s=>/^\{\d+\}$/.test(s)?'(.+?)':s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('')+'$'),values}));
export function translateWebsite(text:string,locale:WebsiteLocale){if(locale==='en'||!text)return text;const key=text.trim(),index=locale==='es'?0:1,entry=websiteTranslations[key];let result=entry?.[index];if(!result)for(const template of templates){const match=key.match(template.regex);if(match){result=template.values[index].replace(/\{(\d+)\}/g,(_,n)=>match[Number(n)+1]);break;}}return result===undefined?text:text.slice(0,text.indexOf(key))+result+text.slice(text.indexOf(key)+key.length);}
