'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Leaderboard} from '@/lib/server/public-leaderboards';
const formatTime=(ticks:number)=>`${Math.floor(ticks/1200)}:${(Math.floor(ticks/20)%60).toString().padStart(2,'0')}.${((ticks%20)*5).toString().padStart(2,'0')}`;
const date=(seconds:number)=>new Date(seconds*1000).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
export default function Leaderboards(){
 const [boards,setBoards]=useState<Leaderboard[]>([]),[query,setQuery]=useState(''),[sort,setSort]=useState('recent'),[checked,setChecked]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(true),[local,setLocal]=useState(false),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[total,setTotal]=useState(0),[summary,setSummary]=useState({tracks:0,scores:0,replays:0});
 const requestId=useRef(0),controller=useRef<AbortController|null>(null);
 const refresh=useCallback(async(nextPage=0)=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;const id=++requestId.current;setBusy(true);try{const response=await fetch('/api/leaderboards?'+new URLSearchParams({q:query,sort,page:String(nextPage)}),{cache:'no-store',signal:AbortSignal.any([abort.signal,AbortSignal.timeout(15000)])}),body=await response.json() as {boards:Leaderboard[];checkedAt:number;error?:string;hasMore:boolean;totalTracks:number;summary:{tracks:number;scores:number;replays:number}};if(!response.ok)throw Error(body.error);if(id===requestId.current){setBoards(before=>nextPage?[...new Map([...before,...body.boards].map(board=>[board.hash,board])).values()]:body.boards);setPage(nextPage);setHasMore(body.hasMore);setTotal(body.totalTracks);setSummary({...body.summary,replays:body.summary.replays??0});setChecked(body.checkedAt);setError('');}}catch(error){if(id===requestId.current&&!abort.signal.aborted)setError(error instanceof Error?error.message:'Could not refresh scores. Try again.');}finally{if(id===requestId.current)setBusy(false);}},[query,sort]);
 useEffect(()=>{setLocal(['localhost','127.0.0.1'].includes(location.hostname));const initial=setTimeout(()=>void refresh(),250),interval=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},3600000),focus=()=>{if(document.visibilityState==='visible')void refresh();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{clearTimeout(initial);clearInterval(interval);controller.current?.abort();requestId.current++;window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);};},[refresh]);
 const filtered=boards;
 return <>
  <section className="scores-hero" aria-labelledby="scores-heading"><div><span className="scores-eyebrow"><i aria-hidden="true"/> GLOBAL HIGH SCORES</span><h2 id="scores-heading">HIGH SCORES.<br/>WORLDWIDE.</h2><p>One track. Seven places. See who made every second count.</p><a href="/#play" className="scores-drive">SET YOUR TIME <span aria-hidden="true">→</span></a></div><div className="scores-summary"><div><strong>{summary.tracks.toLocaleString()}</strong><span>TRACKS RANKED</span></div><div><strong>{summary.scores.toLocaleString()}</strong><span>SHARED TIMES</span></div><div><strong>{summary.replays.toLocaleString()}</strong><span>WATCHABLE REPLAYS</span></div><p>Same verified times as the game.<br/>Different track contents, separate boards.</p></div></section>
  {local&&<aside className="scores-local">LOCAL PREVIEW · These are isolated local test scores, not the live leaderboard.</aside>}
  <section className="scores-directory" aria-label="Track leaderboards"><div className="scores-tools"><div className="scores-search"><label htmlFor="score-search">FIND A TRACK, DRIVER OR CAR</label><input id="score-search" type="search" value={query} onChange={event=>{setQuery(event.target.value);}} placeholder="Search the leaderboards…"/></div><div className="scores-sort"><label htmlFor="score-sort">SORT TRACKS</label><select id="score-sort" value={sort} onChange={event=>{setSort(event.target.value);}}><option value="recent">Recently updated</option><option value="name">Track name A–Z</option></select><svg className="scores-sort-chevron" width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 9 6 6 6-6" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg></div><button className="scores-refresh" disabled={busy} onClick={()=>void refresh()}>{busy?'Refreshing…':'Refresh scores'} <span aria-hidden="true">↻</span></button></div>
  <div className="scores-update" role="status" aria-live="polite"><span>{checked?`Checked ${new Date(checked).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',hour12:false})}`:busy?'Loading shared times…':'Not checked yet'} · Refreshes hourly and when you return</span><span>{total} {total===1?'track':'tracks'}{query?' found':''}</span></div>
  {error&&<p className="scores-error" role="alert">{error}{checked?' Previously loaded times are still shown.':''}</p>}
  {!busy&&!error&&!filtered.length&&<div className="scores-empty"><span aria-hidden="true">—</span><h3>{query?'No matching tracks':'The grid is waiting.'}</h3><p>{query?'Try another track, driver or car name.':'Finish a qualifying race and your track’s leaderboard will appear here.'}</p>{query?<button onClick={()=>setQuery('')}>Clear search</button>:<a href="/#play">Let’s drive →</a>}</div>}
  <div className="scores-boards">{filtered.map(board=><article className="scores-board" key={board.hash} aria-labelledby={'track-'+board.hash}><header><div><span className="scores-track-label">TRACK LEADERBOARD</span><h3 id={'track-'+board.hash}>{board.name}</h3></div><span className="scores-best"><small>TRACK RECORD</small><strong>{formatTime(board.scores[0].ticks)}</strong></span></header><div className="scores-table-wrap"><table><caption className="scores-sr">Fastest seven times for {board.name}</caption><thead><tr><th scope="col">#</th><th scope="col">DRIVER / CAR</th><th scope="col">TIME</th><th scope="col">DETAILS</th></tr></thead><tbody>{board.scores.map((score,index)=><tr key={score.id} className={index===0?'scores-winner':undefined}><td><span className="scores-rank">{String(index+1).padStart(2,'0')}</span></td><td><strong className="scores-driver">{score.driver}</strong><span className="scores-car">{score.car}</span></td><td className="scores-time"><strong>{formatTime(score.ticks)}</strong>{index>0&&<small>+{((score.ticks-board.scores[0].ticks)/20).toFixed(2)}s</small>}</td><td><details className="scores-details"><summary>Run details</summary><p>Posted {date(score.postedAt)}<br/>Car: {score.carCode}<br/>{score.opponent?`Opponent: ${score.opponent}${score.opponentAhead?' (finished ahead)':''}`:'Solo race'}</p>{score.replay?<a href={'/api/replays?id='+score.id} download>Download replay ↗</a>:<span>No public replay</span>}</details>{score.replay&&<span className="scores-replay-dot" title="Public replay available">REPLAY</span>}</td></tr>)}</tbody></table></div><footer><span>{board.scores.length} / 7 places filled</span><details><summary>Track identity</summary><code>{board.hash}</code><p>Filenames can differ. Matching file contents share this board.</p></details></footer></article>)}</div>
  {hasMore&&<button disabled={busy} className="scores-more" onClick={()=>void refresh(page+1)}>Load more tracks ({Math.max(0,total-boards.length)} remaining)</button>}
  <p className="scores-fair">Fresh, completed races only. Replay continuation is not eligible. Names are anonymous; common profanity is masked. <a href="/faq#global-scores">Read the scoring rules ↗</a></p>
  </section>
 </>;
}
