[sdl]
autolock=false
[dosbox]
machine=svga_s3
memsize=16
[render]
frameskip=0
aspect=false
scaler=none
[cpu]
core=auto
cycles=12000
[mixer]
rate=44100
blocksize=1024
prebuffer=20
[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
oplmode=opl2
[autoexec]
@echo off
mount c .
c:
stunts.com
exit
