import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
import {retainRunHistorySQL,pruneRunHistorySQL} from '../lib/server/run-history.ts';import {driverKey,resolvedDriverSQL,combinedCarScoresSQL,pruneCarScoresSQL} from '../lib/server/leaderboard-ranking.ts';import {GLOBAL_SCORE_RULES,scoreString} from '../lib/game/global-score-format.ts';import {publicScoreName} from '../lib/game/public-score-name.ts';
const record=(name:string,car:string)=>{const r=Array(52).fill(0);[...name].forEach((c,i)=>r[i]=c.charCodeAt(0));[...car].forEach((c,i)=>r[17+i]=c.charCodeAt(0));return r;};
test('history keeps the latest five verified attempts across cars, including slower non-ranking runs',()=>{
 const db=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>/^\d+.*\.sql$/.test(f)).sort())db.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
 for(let i=0;i<8;i++){const car=i%2?'FGTO':'PMIN',r=record(i%2?' MARCO ':'Marco',car),id=i.toString(16).padStart(64,'0');db.prepare('INSERT INTO global_scores VALUES (?,?,?,?,?,?,?,?,?)').run(id,GLOBAL_SCORE_RULES,'track',car,1200+i,JSON.stringify(r),100+i,driverKey(r,id),'not_assessed');db.prepare(retainRunHistorySQL).run(GLOBAL_SCORE_RULES,'track');db.prepare(pruneRunHistorySQL).run(GLOBAL_SCORE_RULES,'track',GLOBAL_SCORE_RULES,'track');db.prepare(pruneCarScoresSQL).run(GLOBAL_SCORE_RULES,'track',GLOBAL_SCORE_RULES,'track');}
 assert.deepEqual(db.prepare('SELECT created_at FROM run_history ORDER BY created_at DESC').all().map(r=>r.created_at),[107,106,105,104,103]);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM global_scores').get()!.n,2);
 const binding={prepare(sql:string){let args:unknown[]=[];return {bind(...values:unknown[]){args=values;return this;},async first(){return db.prepare(sql).get(...args as never[]);},async all(){return {results:db.prepare(sql).all(...args as never[])}}};}};
 const source=readFileSync(new URL('../app/api/run-history/route.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/export async function/g,'async function');
 const get=new Function('env','GLOBAL_SCORE_RULES','scoreString','driverKey','resolvedDriverSQL','combinedCarScoresSQL','publicScoreName',stripTypeScriptTypes(source)+';return GET;')({DB:binding},GLOBAL_SCORE_RULES,scoreString,driverKey,resolvedDriverSQL,combinedCarScoresSQL,publicScoreName) as (r:Request)=>Promise<Response>;
 return (async()=>{const response=await get(new Request('https://example.test/api/run-history?score='+('0'.repeat(64))));assert.equal(response.status,200);const body=await response.json() as {runs:{postedAt:number;ranked:boolean;carCode:string}[]};assert.deepEqual(body.runs.map(r=>r.postedAt),[107,106,105,104,103]);assert.ok(body.runs.every(r=>!r.ranked));assert.equal(new Set(body.runs.map(r=>r.carCode)).size,2);assert.equal((await get(new Request('https://example.test/api/run-history?score=invalid'))).status,400);assert.equal((await get(new Request('https://example.test/api/run-history?score='+('f'.repeat(64))))).status,404);db.close();})();
});
test('empty and censored display names are not merged as identities',()=>{assert.notEqual(driverKey(record('','PMIN'),'a'),driverKey(record('','PMIN'),'b'));assert.notEqual(driverKey(record('FUCK','PMIN'),'a'),driverKey(record('SHIT','PMIN'),'b'));assert.equal(driverKey(record(' Marco ','PMIN'),'a'),driverKey(record('MARCO','FGTO'),'b'));});
