import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {recentRacesSQL,recentRace,type RecentRaceRow} from '../lib/server/recent-races.ts';
import {GLOBAL_SCORE_RULES} from '../lib/game/global-score-format.ts';
const record=(name:string)=>{const r=Array(52).fill(0);[...name].forEach((c,i)=>r[i]=c.charCodeAt(0));[...'Porsche/March INDY'].forEach((c,i)=>r[17+i]=c.charCodeAt(0));return JSON.stringify(r);};
test('Recent races deduplicate, limit to eight, exclude withdrawals and classify only evidenced achievements',()=>{
 const db=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>/^\d+.*\.sql$/.test(f)).sort())db.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
 const add=(id:string,ticks:number,stamp:number,driver='marco',assessment='full_route',track='default')=>{db.prepare('INSERT INTO global_scores VALUES (?,?,?,?,?,?,?,?,?)').run(id,GLOBAL_SCORE_RULES,track,'PMIN',ticks,record(driver),stamp,driver,assessment);};
 add('old',1500,1);add('record',1300,2);add('slow',1800,3);add('exploit',500,4,'other','shortcuts_detected');add('uncertain',600,5,'unknown','not_assessed');add('valid',1600,6,'alain');add('withdrawn',100,7,'marco','full_route','test');
 db.prepare('INSERT INTO run_history SELECT * FROM global_scores WHERE id=?').run('record');
 add('older1',1900,-1);add('older2',2000,-2);add('older3',2100,-3);
 const rows=db.prepare(recentRacesSQL).all(GLOBAL_SCORE_RULES,JSON.stringify(['test'])) as RecentRaceRow[];
 assert.equal(rows.length,8);
 assert.deepEqual(rows.slice(0,5).map(r=>r.id),['valid','uncertain','exploit','slow','record']);
 assert.deepEqual(rows.slice(0,5).map(r=>recentRace(r).event),['valid','submitted','submitted','valid','record']);
 assert.equal(recentRace(rows[4]).driver,'marco');
 const base=rows[0];assert.equal(recentRace({...base,driver_key:'alain',previous_best:1700,current_record:1300,previous_record:1300}).event,'improved');
 assert.equal(recentRace({...base,driver_key:'anonymous:x',previous_best:1700}).event,'valid');
 assert.equal(recentRace({...base,driver_key:'',previous_best:1700}).event,'valid');
 db.close();
});
