import {WebsiteText,WebsiteElement} from '@/app/WebsiteLanguage';
import type {Metadata} from 'next';
import Image from 'next/image';
import type {ReactNode} from 'react';
import StuntsBrand from '../StuntsBrand';
import StuntsNavigation from '../StuntsNavigation';

export const metadata:Metadata={
 title:'FAQ — Play Stunts',
 description:'Answers about playing Stunts, global high scores, community tracks, enhanced graphics, replays, personal saves and local builds.',
 alternates:{canonical:'/faq'},
 openGraph:{url:'https://playstunts.com/faq',title:'FAQ — Play Stunts',description:'Playing Stunts, global high scores, community tracks, graphics, replays and personal saves.'},
};

const Section=({id,kicker,title,children}:{id:string;kicker:string;title:string;children:ReactNode})=><section className="faq-section" id={id} aria-labelledby={`${id}-heading`}>
 <div className="faq-section-heading"><span>{kicker}</span><h2 id={`${id}-heading`}>{<WebsiteText text={title}/>}</h2></div>
 <div className="faq-list">{children}</div>
</section>;

const Answer=({question,children,open=false}:{question:string;children:ReactNode;open?:boolean})=><details className="faq-answer" open={open}>
 <summary><span>{<WebsiteText text={question}/>}</span><span className="faq-marker" aria-hidden="true">+</span></summary>
 <div>{children}</div>
</details>;

export default function FaqPage(){return <main className="game-shell stunts-universe faq-page">
 <header className="stunts-masthead">
  <div className="stunts-masthead-brand"><h1><WebsiteElement as="a" href="/" aria-label="Play Stunts home"><StuntsBrand/></WebsiteElement></h1><p className="stunts-developer-credit"><WebsiteText text={"BY DISTINCTIVE SOFTWARE, THE DEVELOPERS OF "}/><span style={{whiteSpace:'nowrap'}}><WebsiteText text={"TEST DRIVE™"}/></span> &amp; <span style={{whiteSpace:'nowrap'}}><WebsiteText text={"THE DUEL: TEST DRIVE II™"}/></span></p></div>
  <div className="stunts-masthead-art" aria-hidden="true"><Image unoptimized width={790} height={309} src="/site/manual-red-car.webp" alt=""/></div>
  <div className="stunts-masthead-copy"><span><WebsiteText text={"PLAYER & PROJECT GUIDE"}/></span><strong><WebsiteText text={"FREQUENTLY ASKED"}/><br/>{' '}<WebsiteText text={"QUESTIONS"}/></strong><p><WebsiteText text={"Playing, global scores, community tracks and personal saves."}/></p></div>
 </header>
 <StuntsNavigation><a href="/#play"><WebsiteText text={"PLAY"}/></a><a href="/#setup"><WebsiteText text={"SETUP"}/></a><a href="/#about"><WebsiteText text={"THE GAME"}/></a><a href="/?view=cars#play"><WebsiteText text={"3D CARS"}/></a><a href="/high-scores"><WebsiteText text={"HIGH SCORES"}/></a><a href="https://pigsgrame.de/downloads/stunts.pdf" target="_blank" rel="noreferrer"><WebsiteText text={"MANUAL"}/></a><a href="/#saves"><WebsiteText text={"TRACKS & REPLAYS"}/></a><a className="nav-play" href="/faq" aria-current="page"><WebsiteText text={"FAQ"}/></a><a href="https://github.com/ACatWithEbola/playstunts" target="_blank" rel="noreferrer"><WebsiteText text={"GITHUB"}/></a></StuntsNavigation>

 <section className="faq-intro" aria-labelledby="faq-intro-heading">
  <div><span className="rail-kicker"><WebsiteText text={"QUICK ANSWERS"}/></span><h2 id="faq-intro-heading"><WebsiteText text={"Start driving."}/><br/>{' '}<WebsiteText text={"Keep your files."}/></h2></div>
  <div><p><WebsiteText text={"PlayStunts brings the 1990 racing and track-building game to a modern browser. Race for shared high scores and discover community tracks on the hosted site, while keeping your personal files in your browser. The open-source reconstruction can also be built locally with a supported original installation."}/></p><div className="faq-actions"><a className="faq-primary" href="/#play"><WebsiteText text={"PLAY STUNTS"}/></a><a href="https://github.com/ACatWithEbola/playstunts#readme" target="_blank" rel="noreferrer"><WebsiteText text={"LOCAL INSTALLATION ↗"}/></a></div></div>
 </section>

 <div className="faq-layout">
  <WebsiteElement as="aside" className="faq-index" aria-label="FAQ sections"><span><WebsiteText text={"ON THIS PAGE"}/></span><a href="#getting-started"><WebsiteText text={"Getting started"}/></a><a href="#graphics-sound"><WebsiteText text={"Graphics & sound"}/></a><a href="#global-scores"><WebsiteText text={"Global high scores"}/></a><a href="#files-saves"><WebsiteText text={"Tracks, replays & saves"}/></a><a href="#local-build"><WebsiteText text={"GitHub & local builds"}/></a><a href="#project-support"><WebsiteText text={"Project & support"}/></a></WebsiteElement>
  <div className="faq-content">
   <Section id="getting-started" kicker="01" title="Getting started">
    <Answer question="What is PlayStunts?" open><p><WebsiteText text={"PlayStunts is a browser-native reconstruction of "}/><em><WebsiteText text={"Stunts"}/></em><WebsiteText text={", also released as "}/><em><WebsiteText text={"4D Sports Driving"}/></em><WebsiteText text={". You can choose from eleven cars, race against the clock or an opponent, build tracks and watch replays."}/></p></Answer>
    <Answer question="Is this an official release?"><p><WebsiteText text={"No. PlayStunts is an independent, unofficial reconstruction and is not affiliated with the original developers, publishers or Roland."}/></p></Answer>
    <Answer question="Do I need to install anything to play here?"><p><WebsiteText text={"No. The hosted game runs directly at "}/><a href="https://playstunts.com"><WebsiteText text={"playstunts.com"}/></a><WebsiteText text={". A local installation is only needed if you want to build the project from GitHub."}/></p></Answer>
    <Answer question="What computer and browser should I use?"><p><WebsiteText text={"A desktop or laptop with a keyboard and a current browser supporting WebAssembly, Web Audio and WebGL is recommended. Browser audio begins after your first click because browsers block automatic sound."}/></p></Answer>
    <Answer question="What are the main controls?"><p><WebsiteText text={"Use the arrow keys to accelerate, brake and steer. "}/><kbd>A</kbd><WebsiteText text={" and "}/><kbd>Z</kbd><WebsiteText text={" shift gears; "}/><kbd><WebsiteText text={"Esc"}/></kbd><WebsiteText text={" opens the game menu; "}/><kbd>C</kbd><WebsiteText text={" or "}/><kbd>F1</kbd>–<kbd>F4</kbd><WebsiteText text={" changes camera; "}/><kbd>D</kbd><WebsiteText text={" toggles the dashboard; and "}/><kbd>V</kbd><WebsiteText text={" cycles the enhanced chase distances. The complete list is beside the game on the home page."}/></p></Answer>
   </Section>

   <Section id="graphics-sound" kicker="02" title="Graphics &amp; sound">
    <Answer question="What is enhanced graphics mode?" open><p><WebsiteText text={"Enhanced mode redraws the race with full-colour scenery, detailed 3D cars, live steering and suspension, improved lighting, shadows and additional chase-camera distances. It is selected by default on the hosted site."}/></p></Answer>
    <Answer question="Can I use the original graphics?"><p><WebsiteText text={"Yes. Enhanced graphics is enabled when the game launches. Choose "}/><strong><WebsiteText text={"Use original graphics"}/></strong><WebsiteText text={" above the game to switch to the display mode selected in Setup. Only that website control changes the renderer; opening an in-game menu does not change your graphics choice."}/></p></Answer>
    <Answer question="Is there a CRT effect?"><p><WebsiteText text={"Toggle "}/><strong><WebsiteText text={"CRT display"}/></strong><WebsiteText text={" above the game for subtle scanlines and shaded edges in either graphics mode. It is off by default and remembered in this browser. The static overlay adds no extra 3D rendering pass."}/></p></Answer>
    <Answer question="What does the audio update change?"><p><WebsiteText text={"The four remixed music cues are enabled when the game launches. Choose "}/><strong><WebsiteText text={"Use original music"}/></strong><WebsiteText text={" to switch back. Sound effects and engine audio remain unchanged. Both versions follow the same playback clock, so changing modes continues at the corresponding position instead of restarting the music. The in-game Options menu still controls whether music is on or off; turning it back on restarts the current score in either version."}/></p></Answer>
    <Answer question="What does Setup change?"><p><WebsiteText text={"Setup selects the original display mode and sound device. Saving changed settings restarts the game automatically. Enhanced graphics remains a separate website option."}/></p></Answer>
    <Answer question="Do I need Roland MT-32 ROMs?"><p><WebsiteText text={"Only for MT-32 sound. You must legally provide compatible control and PCM ROMs yourself when building locally. PC speaker, Tandy, AdLib and Sound Blaster options do not require Roland ROMs."}/></p></Answer>
    <Answer question="Are the cars in the showroom the same as the cars in the race?"><p><WebsiteText text={"Yes. The 3D showroom and enhanced race renderer use the same decoded models and materials for all eleven cars. In the showroom, drag to rotate, scroll to zoom and choose the available source colours."}/></p></Answer>
   </Section>

   <Section id="global-scores" kicker="03" title="Global high scores">
    <Answer question="Are high scores shared with everyone?" open><p><WebsiteText text={"Yes. On playstunts.com, the original in-game high-score table shows the seven fastest named drivers for the selected track, with each driver shown once, shared across players and computers. Times use the original minutes-and-seconds display, with the car and opponent recorded alongside the driver’s name."}/></p></Answer>
    <Answer question="Can one driver fill the leaderboard?"><p><WebsiteText text={"The website shows one fastest run per named driver overall, or for the selected car, in a single table with route badges. Names are grouped ignoring case and surrounding spaces, not verified accounts; unnamed runs stay separate. Race results qualify against your car and assessed category."}/></p></Answer>
    <Answer question="How do I submit a time? Do I need an account?"><p><WebsiteText text={"Finish a fresh race and enter your name using the normal in-game high-score screen when your time qualifies. No account or extra in-game menu is needed. Names are public, anonymous and not reserved, so a name does not prove a player’s identity."}/></p></Answer>
    <Answer question="What makes a race eligible?"><p><WebsiteText text={"A run must finish and pass server verification using the original game simulation, including its route checks and penalties. Using "}/><strong><WebsiteText text={"Continue driving"}/></strong><WebsiteText text={" from a replay makes that run ineligible, even if you continue from the end of the recording. Choose "}/><strong><WebsiteText text={"Restart"}/></strong><WebsiteText text={" to begin a new eligible race. Simply watching a replay does not submit a score."}/></p></Answer>
    <Answer question="Are shortcuts allowed?"><p><WebsiteText text={"Yes. Original penalties still apply. Small grass cuts back onto the same section, either divided-road lane and driving through the inside of loops or left/right corkscrews are allowed. Full run means a complete route was confirmed. Other runs show Possibly exploited: a shortcut was detected or full-route evidence was inconclusive. Keep your replay for review if you dispute it. Uploading an RPL does not submit a score."}/></p></Answer>
    <Answer question="Can I recheck a run without sharing its replay?"><p><WebsiteText text={"Yes. On the home page, expand "}/><strong><WebsiteText text={"High-score replays → Your verified runs"}/></strong><WebsiteText text={" and choose "}/><strong><WebsiteText text={"Recheck privately"}/></strong><WebsiteText text={". It updates the public route label without publishing a private recording. Use the browser you raced in; a time alone is not enough."}/></p></Answer>
    <Answer question="How often does the High Scores page update?"><p><WebsiteText text={"It loads current scores when opened, refreshes hourly while visible and refreshes when you return. Choose "}/><strong><WebsiteText text={"Refresh scores"}/></strong><WebsiteText text={" to check immediately."}/></p></Answer>
    <Answer question="Are older shared replays checked automatically?"><p><WebsiteText text={"Yes. High Scores page refreshes check public replays once per verifier version and update their route category, not their time or driver details. Private recordings require Recheck privately. Inconclusive runs show Possibly exploited; failed checks retry later."}/></p></Answer>
    <Answer question="Which tracks come with the game?"><p><WebsiteText text={"DEFAULT, BERNIES, CHERRIS, HELENS, JOES and SKIDS—the original six. Personal tracks, the editor and Community tracks → Share track remain available."}/></p></Answer>
    <Answer question="Why did a verified run not appear on the leaderboard?"><p><WebsiteText text={"The leaderboard keeps your best qualifying time. Your five most recent verified submissions can appear in recent runs with their public replays, including slower attempts. Full run is an assessed category, not a selectable racing mode."}/></p></Answer>
    <Answer question="Can I see a driver’s recent attempts?"><p><WebsiteText text={"Hover, focus or tap their name on High Scores for up to five most recent retained verified runs on that track, across cars, including non-ranking attempts. Names are not accounts; older discarded runs are unavailable."}/></p></Answer>
    <Answer question="Are replays required for high scores?"><p><WebsiteText text={"Yes. Submitting a high score requires confirmation that its replay will be public. The server verifies and stores the recording with the score. Skipping submission uploads nothing. Ordinary in-game replay saving stays private."}/></p></Answer>
    <Answer question="How are scores checked for cheating?"><p><WebsiteText text={"The server replays the submitted driving inputs and checks the finish time, car and opponent rather than trusting a typed time. Incomplete runs, invalid recordings and mismatched results are rejected. This is not a guarantee against every form of cheating: a modified client can conceal replay continuation or generate automated driving inputs, and anonymous names can be copied."}/></p></Answer>
    <Answer question="Does renaming or changing a track affect its scores?"><p><WebsiteText text={"Boards are identified by the exact track-file contents, not the filename. Renaming the same track keeps the same board; changing its contents creates a separate board. Community tracks use this same system."}/></p></Answer>
    <Answer question="What happens if I lose my internet connection?"><p><WebsiteText text={"Pending submissions are kept in this browser and retried when connectivity returns or you next start the game. The website’s score-status message shows pending, accepted or rejected submissions. Keep the browser’s site data until pending times have synchronized. Older local high-score files are not automatically uploaded to the global board."}/></p></Answer>
   </Section>

   <Section id="files-saves" kicker="04" title="Tracks, replays &amp; saves">
    <Answer question="Can I import tracks from the original game?" open><p><WebsiteText text={"Yes. Open "}/><strong><WebsiteText text={"Tracks, replays and save backups"}/></strong><WebsiteText text={" on the home page and upload an original "}/><code><WebsiteText text={".TRK"}/></code><WebsiteText text={" file. Supported tracks are 1,802 bytes."}/></p></Answer>
    <Answer question="Can I import and watch original replays?"><p><WebsiteText text={"Yes. Upload the "}/><code><WebsiteText text={".RPL"}/></code><WebsiteText text={" file before starting the game, then load it from the in-game replay menu. Names may contain 1–8 letters, numbers, underscores or hyphens, and supported recordings contain no more than 12,000 frames."}/></p></Answer>
    <Answer question="How do I share a track with everyone?"><p><WebsiteText text={"Open "}/><strong><WebsiteText text={"Community tracks"}/></strong><WebsiteText text={" on the home page and choose "}/><strong><WebsiteText text={"Share track (.TRK)"}/></strong><WebsiteText text={". The server validates the original track file and checks that it has one start and a complete route before publishing it. Importing a track into your personal saves does "}/><strong><WebsiteText text={"not"}/></strong><WebsiteText text={" publish it automatically."}/></p></Answer>
    <Answer question="How do I play a community track?"><p><WebsiteText text={"Choose "}/><strong><WebsiteText text={"Add to my game"}/></strong><WebsiteText text={" in Community tracks before starting the game, then select it through the original "}/><strong><WebsiteText text={"Track → Load"}/></strong><WebsiteText text={" menu. You can also download its original "}/><code><WebsiteText text={".TRK"}/></code><WebsiteText text={" file. Sharing the same file again does not create a duplicate public track."}/></p></Answer>
    <Answer question="What files can I upload?"><p><WebsiteText text={"Personal imports accept validated original "}/><code><WebsiteText text={".TRK"}/></code><WebsiteText text={" tracks and "}/><code><WebsiteText text={".RPL"}/></code><WebsiteText text={" replays. The save-backup restoration feature also accepts the supported JSON backup format, with every contained game file checked. Community sharing accepts only validated "}/><code><WebsiteText text={".TRK"}/></code><WebsiteText text={" files; unrelated files and malformed data are rejected."}/></p></Answer>
    <Answer question="Where are my tracks, replays and settings stored?"><p><WebsiteText text={"Your personal tracks, replays, settings and save backups remain local to your browser and the exact site address you use. They are not attached to an account or automatically synchronized between devices. Global high scores and tracks you explicitly share are stored online and visible to other players."}/></p></Answer>
    <Answer question="How do I move my saves to another browser or computer?"><p><WebsiteText text={"Export a save backup from the home page before changing browser, computer, hostname or port. Import that backup at the new address. Individual track and replay downloads preserve their original DOS filenames and bytes."}/></p></Answer>
    <Answer question="What happens if I clear my browser’s site data?"><p><strong><WebsiteText text={"Kept online:"}/></strong><WebsiteText text={" accepted global scores, shared tracks and published replays while ranked or among the driver’s five recent verified runs on that track. Bundled content and files downloaded to your computer are unaffected."}/></p><p><strong><WebsiteText text={"Lost locally:"}/></strong><WebsiteText text={" personal tracks, replays, settings, pending scores and private verified recordings. Export a save backup and let pending scores upload first. There is no account-based restore; backups do not include pending scores or private verification recordings."}/></p></Answer>
    <Answer question="Can everyone watch my high-score replay?"><p><WebsiteText text={"New submitted scores include public replays, available while ranked or among your five most recent verified runs on that track. Slower submitted attempts can appear in recent runs. Old private recordings are not shared retroactively. Importing an RPL cannot create a score."}/></p><p><WebsiteText text={"Public submissions have a 10-minute replay limit. Others can download a replay or add it to their game before starting, then use Options → Load Replay."}/></p></Answer>
   </Section>

   <Section id="local-build" kicker="05" title="GitHub &amp; local builds">
    <Answer question="Does a local build also have global scores?"><p><WebsiteText text={"The repository’s "}/><strong><WebsiteText text={"main"}/></strong><WebsiteText text={" branch retains the local-score edition. The hosted online edition is maintained on "}/><a href="https://github.com/ACatWithEbola/playstunts/tree/feature/global-highscores" target="_blank" rel="noreferrer"><strong><WebsiteText text={"feature/global-highscores"}/></strong> ↗</a><WebsiteText text={" and requires its database service. Its local test database is separate from the live site. See the branch’s README and global-high-score documentation for setup details."}/></p></Answer>
    <Answer question="Are the original game files included on GitHub?" open><p><WebsiteText text={"No. The repository contains the reconstruction source, preparation tools and redistributable dependencies. You must supply your own compatible original game files, and optional Roland ROMs, artwork and box scans are not included."}/></p></Answer>
    <Answer question="Which original game version is supported?"><p><WebsiteText text={"Use the complete extracted PC installation of Mindscape’s "}/><strong><WebsiteText text={"4D Sports Driving 1.1, finalized 13 December 1990"}/></strong><WebsiteText text={", identified as "}/><strong><WebsiteText text={"MS 1990"}/></strong><WebsiteText text={" in the "}/><a href="https://wiki.stunts.hu/wiki/Game_versions" target="_blank" rel="noreferrer"><WebsiteText text={"Stunts version table ↗"}/></a><WebsiteText text={". The community archive named "}/><strong><WebsiteText text={"4D Sports Driving 1.1, Dec 13"}/></strong><WebsiteText text={" is a tested input."}/></p></Answer>
    <Answer question="Will the original copy-protection crash occur locally?"><p><WebsiteText text={"The reconstructed browser game does not execute the original DOS launch programs or their copy-protection path. The current preparation and smoke-check process supports the tested, unmodified original files and verifies that a fresh race continues beyond the original protection interval."}/></p></Answer>
    <Answer question="Why can a local copy look different from playstunts.com?"><p><WebsiteText text={"The hosted site uses optional presentation artwork, including the masthead, box scans and reconstructed title images. These are not required for gameplay and are not distributed in the source repository. A local build uses its documented fallbacks unless you provide permitted copies yourself."}/></p></Answer>
    <Answer question="Where are the complete installation instructions?"><p><WebsiteText text={"The maintained commands, supported checksums, optional artwork layout and troubleshooting steps are in the "}/><a href="https://github.com/ACatWithEbola/playstunts#readme" target="_blank" rel="noreferrer"><WebsiteText text={"GitHub README ↗"}/></a><WebsiteText text={". Follow the steps in order and do not merge newly generated assets into an older installation."}/></p></Answer>
   </Section>

   <Section id="project-support" kicker="06" title="Project &amp; support">
    <Answer question="Is the reconstruction finished?" open><p><WebsiteText text={"Not yet. PlayStunts is a public beta. The main game, Setup, cars, tracks, replays, sound choices and enhanced renderer are available, but visual, audio or simulation differences may still be found."}/></p></Answer>
    <Answer question="How can I support the project?" open><p><WebsiteText text={"I’ve probably spent well over $1,500 of my own money on reconstructing Stunts so far, alongside a huge amount of time and work. If you enjoy the project and would like to help me continue developing it and eventually reconstruct other classic DOS games, any donation is genuinely appreciated. Every bit helps make future projects possible."}/></p><WebsiteElement as="a" href="https://www.paypal.com/donate/?hosted_button_id=YJDJRZW6FEAUN" target="_blank" rel="noopener noreferrer" aria-label="Donate to PlayStunts with PayPal" style={{display:'inline-flex',alignItems:'center',gap:'0.65rem',padding:'0.75rem 1rem',border:'1px solid #35596b',borderRadius:'6px',background:'#142b3a',color:'#fff',textDecoration:'none',fontWeight:700}}><svg width="30" height="32" viewBox="0 0 24 28" aria-hidden="true"><path fill="#0070e0" d="M7 1h9c6 0 8 3 7 8-1 5-4 8-10 8h-3l-2 10H2L7 1z"/><path fill="#00b8f0" d="M10 7h8c5 0 7 3 6 7-1 5-4 7-9 7h-3l-1 6H6l4-20z"/><path fill="#003087" d="M10 7h8c2 0 4 .5 5 1-1 6-4 9-10 9h-3l-2 10H6l4-20z"/></svg><span><WebsiteText text={"Donate with PayPal ↗"}/></span></WebsiteElement></Answer>
    <Answer question="How do I report a problem?"><p><a href="mailto:svenanders@lokaas.net?subject=PlayStunts%20bug%20report"><WebsiteText text={"Send a bug report"}/></a><WebsiteText text={" with your browser, selected car, track or replay, sound and display settings, and the steps needed to reproduce it. Do not attach game archives, ROMs or credentials."}/></p></Answer>
    <Answer question="Can I inspect or contribute to the source?"><p><WebsiteText text={"Yes. The reconstruction is available on "}/><a href="https://github.com/ACatWithEbola/playstunts" target="_blank" rel="noreferrer"><WebsiteText text={"GitHub ↗"}/></a><WebsiteText text={". Original project source is licensed under GPL-3.0-only unless a file states otherwise; third-party components keep their own licences."}/></p></Answer>
    <Answer question="Does the source-code licence include the original Stunts material?"><p><WebsiteText text={"No. The project licence does not cover original executables, artwork, game data, Roland ROMs or material extracted from those files. Those remain subject to their respective rights holders’ terms."}/></p></Answer>
   </Section>
  </div>
 </div>

 <footer className="faq-footer"><div><strong><WebsiteText text={"PLAYSTUNTS.COM"}/></strong><p><WebsiteText text={"Unofficial browser reconstruction · Public beta"}/></p></div><WebsiteElement as="nav" aria-label="Footer links"><a href="/"><WebsiteText text={"Home"}/></a><a href="https://pigsgrame.de/downloads/stunts.pdf" target="_blank" rel="noreferrer"><WebsiteText text={"Manual"}/></a><a href="https://github.com/ACatWithEbola/playstunts" target="_blank" rel="noreferrer"><WebsiteText text={"GitHub"}/></a><a href="mailto:svenanders@lokaas.net?subject=PlayStunts%20bug%20report"><WebsiteText text={"Report a bug"}/></a></WebsiteElement></footer>
 </main>}
